:PROPERTIES:
:ID:       87311E45-03D5-4E57-9D8A-A1BAACB6539F
:END:
#+TITLE: parlimentarism recidivus

Tags: [[id:5D4FD56C-329E-4881-AEBC-EFE6DDF0F29D][articles]]

Review of Parliamentarism: From Burke to Weber, by William Selinger, and Parliament the Mirror of the Nation: Representation, Deliberation, and Democracy in Victorian Britain, by Gregory Conti
- https://www.instapaper.com/read/1297320439

Claims that we've missed the power of the parlimentarism machine. Power radiated from the purse, and the House of Commons controlled all bills.

France refined parlimentarism in the wake of the French Revolution and theorized the concepts in the 18th century.

Leading to:
- Britan as classical parliamentary theory: consitutional monarchs who reigned but did not govern.
  - Queen acted as an upper ceiling

Parliament as a mirror of the nation means a multifacted understanding of what is being mirrored. Things are like a terrain of battle, and the meaning of mirroring/right way of mirroring was peaking in the 19th century.

Conti's Victorian thinkers believed that Parliament being a mirror means reflecting all the salient divisions of the nation.

_For many years now, scholars of political thought have focused on the origins of liberalism, the perceived tension between “liberalism” and “republicanism,” and the notions of freedom that underpin each. This has led to a special interest in the 18th century as a time of political founding, and a particular concern with the classical authors on which Enlightenment political thinkers frequently drew._

- https://www.journalofdemocracy.org/articles/the-danger-of-deconsolidation-the-democratic-disconnect/

Understanding of represenative democracies has more than currently being offered, ideas in the 18th and 19th century has more to discover.

Implict is the understanding that there is not an equal judicial "constitutional court" because the free legaslative assembly would be making the power.
- _Juristocracy would have been just another form of tyranny_
#+SETUPFILE:./hugo_setup.org
