:PROPERTIES:
:ID:       A12E1BC3-77E4-4EF3-A9D3-367AC8F7BE28
:END:
#+TITLE: Nationalism and Outsiders in the Middle East - Midterm Final

Tags: [[id:300022C0-7BEB-468C-A370-069F1EF4759E][Nationalism and Outsiders in the Middle East - Midterm Draft]]

Question 1
    Nationalism today must be defined within the Middle East as two broad components: a more "traditional" inner component derived from the nation-state, and another outer component derived from the modern empires of the world. Anthony Smith defines nationalism as "language and symbolism, a sociopolitical movement and an ideology of the nation'' (Smith, 7). The component is easily observable within the Middle East, as contemporary nations within the region offer a wide range of examples speaking to each aspect that Smith describes. However, a second less observable component is described by Chaterjee, who puts forward the notion that empires today, although they lack explicit annexation and overt repression, impose their own forms of nationalism onto the region.
    To first look at the observable aspects of nationalism within the region, one can easily find abundant examples of the three aspects Smith describes. One example of the symbolism of nationalism can be found within Syria. The boundaries of the Syrian Arab Republic were drawn as part of the French Syrian mandate, partitioning out the modern Lebanese state and several autonomous regions, such as the Druze state and the Sanjak of Alexandretta. However, while the modern Lebanese state is formally recognized by the Syrian state as an independent nation today, and the Druze and Alawite states were absorbed back into Syria, it is notable that the Sanjak of Alexandretta eventually transitioned into the Hatay State for one year under League of Nations supervision, then absorbed into the Turkish state as the Hatay province following a referendum. Modern Syria still holds this referendum as illegitimate, and the Syrian Democratic Forces still depicts Hatay province as part of Syria within its flag today. This commonality between the Syrian state and the SDF, with one side going as far as to depict it upon a flag, denotes a special quality to the nature of a Syrian nation and provides a guidepost towards irredentialist conceptions. With the SDF flag as an explicit symbol, the agreement between two warring factions on the boundaries of Syria is a textbook example of Smith's conception of nationalism.
    Socialpolitical movements within the Middle East are the most visible aspects of nationalism within the region. As these movements specifically emphasize  cultural gestation and representation (Smith 6), the issues of Palestine and Kurdish independence are both representative here. Both groups are circumscribed both legally and culturally. Palestinians living in Jordan, for example, are allowed to travel to the Palestinian territories, while Jordanians are not, but certain conditions bar Palestinians living in Jordan from acquiring a Jordanian passport. In the case of Kurds, a patchwork of laws spread across four nations carved up the definition of Kurds, from the de facto independence in Syria, outright repression within Turkey, and state-granted autonomy within Iraq and Iran. By mostly formalizing these ethnic categories into law, states within the Middle East perform segregative biopolitics via passport control in order to contain and control nationalist ideologies. The auspices of the modern nation-state's boundaries act as a buffer on nationalism within the Palestinian and Kurdish groups.
The final aspect of Smith's definition of nationalism is nationalism as a legal entity, which places the nation-state at the center as both a sovereign to be obeyed and spoils to be captured. Lebanon and Iraq are clear examples here. Lebanon's taif system, and Iraq's unwritten-but-similar system of carving up political roles between factions is exactly representative of this, the Lebanese and Iraqi states both maintain that they are the only source of legitimate violence, but different roles are split among factions for patronage purposes. The act of agreeing on the boundaries of a nation-state to carve up is itself a veneration of the nation-state idea. This must be distinguished from the cases of Palestine and Kurds brought up in relation to social political movements. In the case of Palestine and Kurds, the nation-state acts as an oppressor, while in the case of Lebanon and Iraq, the status of factions is formalized in legal or normative rulings.
    Nationalism within the Middle East is not solely confined to within the nations. Chatterjee has shown that the binding of capitalism and the nation-state have worked in tandem to formalize both. Yet, as capitalism and the flow of capital itself has grown, it has allowed empires to continue within the space of capital. Modern imperialism within the Middle East is not preoccupied with the explicit annexation of territory or people, but rather interested in the control and usage of capital. The International Monetary Fund's loan to Egypt in 2016 in exchange for structural adjustments, as well as Lebanon's peg of the Lebanese Lira to the US Dollar are both examples of a foriegn nationalism. Both countries have ceded sovereign control of their currency to either an international organization in the case of Egypt, or another country in the case of Lebanon. Nationalism continues to be important in providing a rallying point against these acts of sovereign capture.



Question 2
The repercussions of colonialism within the Middle East is most apparent within the context of the Iraqi state. Dogged by the "artificial state" narrative within modern literature, Iraq continues to show the impacts of colonial legacy, especially in the development of Iraqi nationalism. British colonialism, the treatment and exploitation of resources within Iraq during the mandate era and the interwar period lead to the outpouring of political movements from minorities, as well as gestated the concept of a greater Iraqi nationalism.
Nationalism must be defined carefully when talking about Iraq. The logic of an artificial state is one intertwined with the notion of an "ethnic" state, where an ethic state comprised of a single ethnicity is the realization of ethnosymbolism. This state is perceived as "natural", in diametric opposition to the "artificial" state, which is composed of heterogeneous groups that act with their own agencies. For historical reasons, the "artificial state" narrative is a useful one, as it provided justification for the British mandate, stating that a young "artificial" state required tutelage before maturation onto the world stage. It must be noted, however, that the development of Iraq at the start of the mandate rivaled the development of the Balkan states, but yet there was no concept of a mandate for the Balkan states (Anscombe, 152).
Furthermore, the idea of an artificial state requires the assumption that the groups and sects within Iraq are transtemporal and unchanging, harkening back to the concepts of primordialism. Kurds, Sunni, Shia, Armenian, Jewish populations must be held to be coherent wholes struggling against one another, yet also these identifications are expected to always have remained and to always remain. In other words, the British practice of patronage across ethnic lines, combined with the imposition of an "artificial" state narrative, combined to generate a feedback loop encouraging the sectarian nature of Iraq today. Benedict Anderson even remarks upon this by stating that the concept of an "imagined community" requires groups to conceptualize a homogenous time (Pursely, 13).
British colonial policy during the Iraqi mandate towards minorities was either co-option or necropolitics. Gertrude Bell famously commented that Iraqi should remain an agricultural country "forever", with intense focus on control of Iraq's oil wealth (Pursely, 35). As a result, mandatory Iraq was mostly run through the Royal Air Force, which proceeded to conduct intense air bombings in order to pacify a rural population, such as the case of the revolt in 1920. The revolt, which was predominantly Shia, was violently put down by the British in support of a Sunni government. Assyrians, who were protected by the British until 1932, leading to greater Iraqi society perceiving them as a privileged class (Simon, 93). Due to this explicit patronage, when the British left, Bakr Sidiqi was able to organize a popular campaign resulting in a massacre of Assyrians. British mandatory and colonial policies, geared towards management of the Iraqi populace by pitting different groups together, sowed the seeds of sectarian based violence and nationalism based on ethnicity.
Sara Pursely's work on segreative biopolitics of gender and masculinity must be noted here. Pursely describes how Sati al-Husri recognized the colonial mentality of education, based on the false psychological theory of the unconscious (72). In this respect, colonialism shaped al-Husri's views by standing in opposition to his later policies, where al-Husri promoted a more egalitarian and inclusive education system, starting by standardizing the core curriculum between boys/girls and urban/rural areas. The British mandatory policy of leaving the Iraqi Ministry of Education to its own devices actually allowed al-Husri to promote his views on pan-Arabism.

However, even as Iraq gained independence in 1932 with the retreat of the British to specific, treaty bound terms, colonialism did not disappear from Iraq. The Monroe Report, which was generated by a group of educators from the Columbia Teachers College during a visit to Iraq, faulted the Ministry of Education for the standardized system of education between boys/girls and urban/rural. Even as one colonial power began to fade, American-style teaching, based on the Tuskegee model (Pursley 87) of "learning by doing" and "adapted education" (Pursley 79) clambered up to the still warm colonial seat. While American influences are not "colonialism" in the strict sense, the influence of the Monroe Report was reminiscent of colonial policies in that it attempted to lift policies geared towards suppression of minorities within the United States and apply them in Iraq. As a result of the Monroe Report and the educated elite who had studied at the Teacher's College, the Ministry of Education began to dismantle some of al-Husri's policies of standardization, such as providing more focus on home economics for girls and focusing school curriculums on encouraging and generating sexual differences. As British indirect rule receded, American influences grew in education policy.
The context of colonialism via capitalistic terms continued in Iraq for quite some time, such as with the Dujayla land project. Overall, colonial rule first via the British then the Americans through international organizations shaped a narrative around the Iraqi state, as well fed into the notions of sect, pushing them more towards ethnosymbolism.


Question 3
Anderson's theory of nations as "imagined communities" predominately revolves around the notion that all nations are imagined, as it is impossible for all citizens within modern nations to meet one another, but is shared nevertheless. The nation, Anderson claims, is one that is founded on ethnolinguistic lines, with emphasis on a shared common language, and socially constructed within the context of a perceived homogenous time frame. It is a modern concept accelerated into existence by decentralization of power, print capitalism, and the standardization of language. Imagined communities seem to apply broadly at first blush to the Middle East, such as the case of pan-Arabism and Turkey, but as Chaterjee and other sources show, the concept of an imagined community is not enough to understand the events of the Middle East.
The standout example of Anderson's theory is Sati al-Husri and his concept of Pan-Arabism. Husri's promotion of a pan-Arab identity, one that transcends religion by emphasizing the commonality of language between Iraqi Sunnis, Shias, Jews, and Christians through the promotion of a standardized education system and spread of literacy is almost a direct act of Anderson's theory. Even the exclusion of Kurds in al-Husri's policies aligns with Anderson's theory, Anderson describes the "elastic boundaries" of nations, which accurately describes the status of the Kurds between the beginning of the Iraqi mandate to the Treaty of Ankara, to the formal independence of Iraq in 1932.
Chaterjee's central critique of Anderson revolves around the fact that there "imagined communities" is a terminal destination. In eliding nationalism and political movements together, it ignores that the borders of post-colonial states were largely drawn by colonial powers and reduces the agency of post-colonial states themselves, claiming that "even our imaginations must remain forever colonized" (Chaterjee, 5). The work of Lale Can with regards to Central Asian pilgrims during the late Ottoman era is an example. The debates within the Ottoman empire with regards to the naturalization of these pilgrims pushes the boundaries that Anderson describes. Even as these pilgrims brought into the idea of print capitalism and perceived themselves within a singular time frame in concert with the Ottoman Empire, the Ottoman Empire attempted to put up various legal roadblocks in order to prevent their naturalization (Can, 151). Even as these pilgrims fulfill the criteria Anderson puts out, the theory of "imagined communities" is not enough to explain why these pilgrims were not incorporated.
Isa Blumi's work on the Ottoman refugees within the Balkans also lends credence to Chaterjee's criticisms. While standardization of language via textbooks and intellectual milieu in Romanian and Bulgaria seem to fit Anderson's critique, the social club Drita, founded in Romania  managed to raise funds across the linguistic spectrum (Blumi, 74). Drita's prolific publications then managed to elicit challenges across multiple states within the Balkans across ethnolinguistic lines, which the theory of "imagined communities" cannot explain. If Romania, Bulgaria, and Albania saw themselves as individual communities, social clubs like Drita could have not existed, as each country standardized on different languages.
   Anderson's theory of imagined communities is appealing, but greater inspection through the history of central and peripheral states show that the theory does not hold up. Some of Anderson's theoretical constructs do apply, such as broad terms of print capitalism and the conception of a perceived homogenous time, but the Middle East has shown that nation-formations develop in more idiosyncratic lines.


Question 5
     Outsiders play a vital role in the shaping of Middle East identities, and in turn, the nationalisms that arose. However, to fully discuss this role, the definition of an "outsider" within the context of the Middle East must be carefully defined. If an "outsider" is simply defined as a privileged class, typically based on ethnolinguistic lines, existing within a bounded state, then the concept of an "outsider" is simply inherited from the colonial and mandate eras. This is apparent within Simon's discussion of Iraqi nationalism, wherein he describes Iraqi nationalism strictly in terms of ethnic and linguistic groups in contrast to the Iraqi Sunnis. Simon's discussion focuses on the plight of the Iraqi Kurds, who longed for their own nation, Iraqi Shias, who comprised a plurality of the population but were deprived proportional representation within the state due to the British demand for a Sunni monarch, Iraqi Jews, whose communities were decimated due to factors outside their control, and the Assyrians, a British patroned group that suffered horrific reprisals as the British retreated.
While it is appealing to carve up the insider/outsider paradigm based on the patronage lines of colonial powers, this framing is fundamentally limited in scope. Patronage lines were based on ethnolinguistic lines, and ethnolinguistic lines presuppose the existence of a permanent, unchanging sectarian identities, almost always tied to specific locations. To understand how outsiders affect nationalism and national identities within the Middle East, I believe it is necessary to expand the framing of who is an outsider. Outsiders are groups that are transtemporal as well as transpatial, outsiders can be born of a different time period as well as belonging to separate groups. The examples of the last Ottoman generation of officiers, who held a vital role in the shaping of mandate states, placed alongside Armenians, Kurds, and Iraqi show how outsiders shaped various states in idiosyncratic ways. The notion of a secular Iraqi state buttressed on sectarian lines arise from the early mandate era, and the existence of an unwritten sect-based state in Iraq today is a direct result of this. Turkish identity is based upon a strong cultural identity and a weak judicial one, leading to the paradox of "privilege" that Adar describes.
Yassine al-Hashimi's role in the construction of Iraqi nationalism cannot be understated. The work of Michael Provonce shows us how al-Hashimi deftly understood the power structures being built by the British to rule Iraq. Although born in Baghdad, al-Hashimi was a member of the last generation of Ottoman sons, and studied at the elite general staff college during the Ottoman twilight years, where he (secretly) became a member of the CUP. During Mustafa Kemal's consolidation of power within Anatolia, al-Hashimi requested to return to Iraq after the coronation of Faiysal (Provence, 137), which, although he was originally born in the city, al-Hashimi was an outsider for having been absent over two decades. His later vocal criticisms of Faiysal based on disagreements about the level of cooperation with the British lead him to be a member of the "opposition". Faiysal's pattern of temporarily appointing al-Hashimi prime minister in order to satisfy Iraqis shows how Iraqi nationalism is based on a rotating cast of power, that compromise is spurned for handouts to certain populations via a spoils system. Reconciliation between various groups in Iraq were not managed by developing true dialogue or "big tent" groups, but rather a management of frustration and anger among various groups. This bears remarkable similarity to the modern Iraqi political system, where prime ministerial candidates require the assent of US-aligned and Iran-aligned groups, and certain ministries are divided between them, while important ministries such as the oil ministry are left to the hands of technocrats. No true dialogue exists between these various groups, rather national identity itself is premised upon carving up the spoils of the state.
Outsiders helped define the boundaries of the early Turkish republic as well, thereby creating the modern Turkish nationalist imaginary. The perceived privileged position of Armenians in the modern Turkish republic (Adar) is a sign of this, while Turkish citizenship is defined as anyone who had lived within Anatolia during the formation of the state, to be a Turk, culturally speaking, is drawn on far more strict lines. Adar talks about how an MP stated that "authentic citizens belongs to the Hanefi sect of Sunni Islam and speaks Turkish". This line neatly cleaves out Armenians and Kurds from "authentic citizenship", providing a root for a nationalist imaginary, distinct from the legal definitions.
Yet the differences between the definition of a Turk in Turkish law and culture also serve to make Turkish identity somewhat malleable. If an Armenian publicly and routinely pledges loyalty to the state, they are considered "privileged" (Adar 743), as they have effectively leveraged their legal status as a Turkish citizen to join the cultural group of "Turks". Furthermore, the Turkish cultural identity can be leveraged to change the legal status as well. The work of Faiz Ahmed in describing the close contact of ex-CUP officers in Afghanistan to the Turkish state displays this, ultimately with Afghanistan under Aman Allah becoming the first nation to recognize the newly created Turkish Republic, all stemming from broad pan-Islamic lines. The powers of these bonds held even after Kemal formally abolished the caliphate. The grey zone created by a distinction of law and culture with regards to Turkish identity provided ample space for the construction of a strong nationalist identity, as it clearly delineated the outsiders while providing enough room to absorb others under its aegis.
#+SETUPFILE:./hugo_setup.org
