:PROPERTIES:
:ID:       0DEB2388-5061-4C4E-B384-A8C1F666089D
:END:
#+SETUPFILE:./hugo_setup.org
#+TITLE: post-ottoman iraq/egypt irrigation paper proposal
#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+OPTIONS: toc:nil

Tags: [[id:A63D0CEC-6083-46C5-BD8D-7A8D750FF1A4][classes]], [[id:A438ACD2-2C1E-40EB-9502-74E5B69EA9FF][Post Ottoman Near East]]

* Abstract
  The opening of the Aswan Low Dam in 1902, as well as the Aswan High Dam in 1960 in Egypt has drawn significant scholarship in modernization theory and environmental history. Notions of modernity within Egyptian society were debated about within the context of both the Low and High dams. Yet curiously little is written about the dams of Iraq, specifically the Hindiya Barrage, opened in 1913, and the Kut Barrage, opened in 1939. These two Iraqi dams provide unique lenses against the scholarship of the Aswan dams within the notions of modernity and development, as the Low Dam and the Hindiya Barrage were constructed under the Ottoman Empire, while the High Dam and the Kut Barrage were constructed after both nations had technically achieved indpendence from the British state. This article examines the technical background, environmental impact, and the modernization trends that took hold in both Egypt and Iraq during these periods.
* Outline
** History of the Aswan Low/High Dam, Hindiya/Kut Barrage
** Current discussions of modernity and current literature the Low and High Dams
** Hindiya barrage
*** William Willcocks and his relationship to the Hindiya barrage and the Aswan Low Dam

*** Young Turks and their influence on the Hindiya barrage
** Kut Barrage
*** Construction by Balfour Betty
*** Purposes of Irrigating the al-Gharraf Region and the Dujayla Projects
*** Importance of the Kut Barrage for King Ghazi's last speech and President Barnam Salih's 2019 visit
** Similar pathways of modernity
*** Miscalculations of Willcocks in the Aswan Low Dam
**** Deprecation of the Hindiya Barrage
*** Orientialist narratives on actual effects of the Aswan Low Dam
**** The need to raise into the Aswan High Dam
**** Orientialist narratives during the al-Gharraf irrigation
** Conclusion
* Potential Bibliography
- [1]A. Mikhail, “AN IRRIGATED EMPIRE: THE VIEW FROM OTTOMAN FAYYUM,” Int. J. Middle East Stud., vol. 42, no. 4, pp. 569–590, Nov. 2010, doi: 10.1017/S0020743810000826.
- [2]“Aswan Dam,” Wikipedia. 22-Feb-2020.
- [3]T. Dodge, “Chapter One: Understanding the drivers of violence in Iraq,” Adelphi Series, vol. 52, no. 434–435, pp. 31–52, Dec. 2012, doi: 10.1080/19445571.2012.758337.
- [4]N. Y. Reynolds, “City of the High Dam: Aswan and the Promise of Postcolonialism in Egypt: City of the High Dam,” City & Society, vol. 29, no. 1, pp. 213–235, Apr. 2017, doi: 10.1111/ciso.12119.
- [5]M. W. Ertsen, “Controlling the farmer: colonial and post- colonial irrigation interventions in Africa,” TDSA, vol. 4, no. 1, Apr. 2008, doi: 10.4102/td.v4i1.167.
- [6]B. Fisk, “Dujaila: Iraq’s Pilot Project for Land Settlement,” Economic Geography, vol. 28, no. 4, p. 343, Oct. 1952, doi: 10.2307/141972.
- [7]M. A. Abu-Zeid and F. Z. El-Shibini, “Egypt’s High Aswan Dam,” International Journal of Water Resources Development, vol. 13, no. 2, pp. 209–218, Jun. 1997, doi: 10.1080/07900629749836.
- [8]T. Cook, “Engineering Modernity: The Aswan Low Dam and Modernizing the Nile,” p. 30.
- [9]S. Pursley, Familiar futures: time, selfhood, and sovereignty in Iraq. Stanford, California: Stanford University Press, 2019.
- [10]K. Frenken, “FAO Land and Water Division,” p. 423.
- [11]A. H. Ismail, M. A. Shareef, and F. M. Alatar, “Hydrochemistry of Groundwater and its Suitability for Drinking and Irrigation in Baghdad, Iraq,” Environ.  Process., vol. 6, no. 2, pp. 543–560, Jun. 2019, doi: 10.1007/s40710-019-00374-x.
- [12]J. Xu, L. Wu, A. C. Chang, and Y. Zhang, “Impact of long-term reclaimed wastewater irrigation on agricultural soils: A preliminary assessment,” Journal of Hazardous Materials, vol. 183, no. 1–3, pp. 780–786, Nov. 2010, doi: 10.1016/j.jhazmat.2010.07.094.
- [13]“Iraq’s Water Woes : A Primer,” p. 6.
- [14]“King Ghazi At Kut Barrage | AP Archive.” [Online]. Available: http://www.aparchive.com/metadata/youtube/27f2accd4419449db4c9bc92cbc4095c. [Accessed: 24-Mar-2020].
- [15]“Kut Barrage - Al-Burhan Group.” [Online]. Available: http://www.alburhangroup.com/our-history-kut-barrage.php. [Accessed: 24-Mar-2020].
- [16]M. H. Nasser, “Land and water resources in Iraq: an updated assessment,” Journal of Arid Environments, vol. 12, no. 3, pp. 191–198, May 1987, doi: 10.1016/S0140-1963(18)31163-7.
- [17]S. A. H. Ouda and A. E.-H. Zohry, Management of Climate Induced Drought and Water Scarcity in Egypt: Unconventional Solutions. Cham: Springer International Publishing, 2016.
- [18]E. Davis, Memories of state: politics, history, and collective identity in modern Iraq. Berkeley: University of California Press, 2005.
- [19]T. Mitchell, Rule of experts: Egypt, techno-politics, modernity. Berkeley: University of California Press, 2002.
- [20]D. E. Armanios, “Sustainable development as a community of practice: insights from rural water projects in Egypt,” Sustainable Development, vol. 20, no. 1, pp. 42–57, 2012, doi: 10.1002/sd.463.
- [21]I. Jackson, “The architecture of the British Mandate in Iraq: nation-building and state creation,” The Journal of Architecture, vol. 21, no. 3, pp. 375–417, Apr. 2016, doi: 10.1080/13602365.2016.1179662.
- [22]J. Swansbourne, “THE DESIGN AND CONSTRUCTION OF THE HINDIYA BRIDGE.,” Proceedings of the Institution of Civil Engineers, vol. 8, no. 1, pp. 1–16, Sep. 1957, doi: 10.1680/iicep.1957.1923.
- [23]N. K. Al-Barazi, “The geography of Argiculture in irrigated areas of the middle Euphrates valley,” Durham theses, 1960.
- [24]R. I. Money, “The Hindiya Barrage, Mesopotamia,” The Geographical Journal, vol. 50, no. 3, p. 217, Sep. 1917, doi: 10.2307/1779909.
- [25]“The Kut Barrage Irrigation Scheme,” Nature, vol. 143, no. 3610, pp. 18–19, Jan. 1939, doi: 10.1038/143018c0.
- [26]M. Provence, The last Ottoman generation and the making of the modern Middle East. 2017.
- [27]J. H. G. Lebon, “The New Irrigation Era in Iraq,” Economic Geography, vol. 31, no. 1, p. 47, Jan. 1955, doi: 10.2307/142410.
- [28]I. P.-P. F. Masum, “The President Visits the Kut Barrage.” [Online]. Available: http://presidency.iq/en/Details.aspx?id=1316. [Accessed: 24-Mar-2020].
- [29]R. W. Rycroft and J. S. Szyliowicz, “The Technological Dimension of Decision Making: The Case of the Aswan High Dam,” World Pol., vol. 33, no. 1, pp. 36–61, Oct. 1980, doi: 10.2307/2010254.
- [30]M. Abdullah, N. Al-Ansari, and J. Laue, “Water Resources Projects in Iraq, Irrigation,” p. 27.
- [31]M. Abdullah, N. Al-Ansari, and J. Laue, “Water Resources Projects in Iraq: Barrages,” p. 15.
