:PROPERTIES:
:ID:       11FC84A7-5EA5-4E09-B50A-23DE8B49DEF0
:END:
#+SETUPFILE:./hugo_setup.org
#+HUGO_SLUG: american_reverie
#+TITLE: american reverie

Tags: [[id:BF94E285-63E1-47AC-B228-2359842F79C7][drafts]]

I recently read an article by [[https://patrickwyman.substack.com/p/imperial-wars-always-come-home][Patrick Wyman on how empires in decline have their wars reverberate back on them]]. The gist of it: empires typically have their domestic affairs shielded away from their foreign actions. It's only when empires are in decline that you see the actions in foreign lands affect things back home. In the case of the US, the failed wars of Iraq and Afghanistan contribute to the militarization of the police and erosion of the rights of domestic citizens, such as the case of Portland and federal paramilitary snatching up protestors.

I agree with Wyman, since 2001, under the arching theme of "never again", American institutions have become more defensive and more brutal[fn:3], becoming what Bruno Macaes calls a "citadel on a hill". However, I want to push Wyman's idea further: recent events, such as the paramilitaries in Portland, the alt-right militias, and even the protests can be traced back to America's foundational culture, the concept of settler colonialism in the "frontier lands" of Westward expansion. Settler colonialism is alive and well in the US, the failures in Iraq and Afghanistan just make them more clear.

Settler colonialism isn't like the typical British/India colonialism, where you have one ruling group (i.e. the British) dominating another group (the Indians). Rather, settler colonialism is about [[https://www.tandfonline.com/doi/full/10.1080/14623520601056240][replacing the indigenous population]], and taking over their lands. This is deeply rooted in American society, it's the foundation to why certain Americans perceive themselves as "real" Americans. These people largely buy into the concept of a "coastal elite", typically hold blue-collar jobs, and likely live in racially/culturally homogenous areas[fn:4]. While there are exceptions, the point is this: there is a group of Americans who perceive themselves as a more legitimate heir to a certain American society than others.

This ideology can be traced back to settler colonialism. Settler colonialism in America allowed for western settlers in the 1800's to buy into this idea of a "blank slate", a tabula rasa where one can manifest their destiny. The "West" was blank, a boundless resource to be exploited. This conveniently sets aside the brutality inflicted on the Native Americans, who had to be forcefully removed from their land in order to create this blank slate.

In conjuction to the the concept of a frontier, the American South exploited its resources through the insitution of slavery. Slavery, at it's core, disposesses people of the fruits of their labor. Slavery takes away the results of what you do in exchange for nothing. Slavery was how the south built its economy, in contrast to the undeveloped west. The question then becomes: why did the US never enslave Native Americans on a mass level? The colonalization of the Midwest plains began in the late 1820's, slavery was not formally abolished until 1865. Enslaving Native Americans would have been a far cheaper source of labor than black slaves, so why was there never any formal institution set up to enslave Native Americans?

The answer is that black slaves /had no collective claims to the land they worked on/. Black slaves, stripped of their heritage and past, could not have any claim that they had settled on the land they worked on, while Native Americans had lived on their lands for generations. These are the twin engines of American settler colonialism, taking away land from the Native Americans, taking away the products of labor from black slaves. Also in the 1800's, [[https://en.wikipedia.org/wiki/On_the_Principles_of_Political_Economy_and_Taxation][David Ricardo formulated the idea of land and its relationship to economics]], and Marx linked the idea of labor and economics. Westward expansion was, above all, an economic project, and it found its base in two populations: Ricardo for the Native American, Marx for the black slave.

It is in this bubble that the first concept of a "real" American begins to form. The frontiersman of westward expansion were only able to expand out onto the pristine plains by driving out the native populations, fueled with tools and wealth generated through slavery. The frontiersman could hold up an image of "self-made", man against nature, even though the conditions that allowed manifest destiny were created through immense suffering of the Native Americans and black slaves.

The American society of the post-World War II era was formed in much of the same way. In the era of the American empire expanding overseas after World War II, Americans found themselves in a similar situation, they could claim to live in a meritocracy where all you had to do was work hard, even though this was based on the suffering of people all over the world. The twin engines that powered America's economy, Native Americans and black slaves, had been replaced with consumers overseas. In the wake of the Cold War, America's manufacturing and export economy required a healthy consumer base, and the only way to achieve that was to corner the global market. Thus the Cold War began, alongside the propping up of brutal dictators to fight against communism. Native peoples in South Vietnam, Chile, and the other countries where the US fought proxy wars or supported brutal regimes did not die for "freedom" or "halting of Communist expansion", they died so that the US could maintain countries to export to. Ultimately, Americans in the Cold War could tell themselves American society was fair and equal, even as the conditions for a "fair and equal" American society was on the backs of millions overseas.

Back to modern day America. Modern day America is reeling from its failures in Iraq and Afghanistan, yet why did the same thing not happen in the wake of the Vietnam war? How did America disengage from Vietnam with, as George Kennan phrased it, "total withdrawal, followed by silence and detachment"[fn:1]?

The answer is television, and by extension, social media. The first war that was made-for-TV was the first Gulf War. Broadcasted on television, the US's quick destruction of Iraqi army in Kuwait shocked the world with American power. Technical superiority, there for all to see. This led to a revival in how other /perceive/ American strength, no longer was America the country that lost a war to South Asian farmers, it was the country with vast technical support that could demolish an army within days, and America was ready to show everyone. The fall of the Soviet Union, only ten months after the end of the first Gulf War, made American society, culture, and military seem all the more indomitable. Television linked together American society, culture, and military and bound together the success of America militarily with the success of American culture. You could root for your fellow countrymen from the safety of your couch.

It is this reviere that Iraq and Afghanistan shake us out of. No matter the technical superiority, the US military was unable to establish a functioning democracy in Iraq, and barely able to rebuild society in Afghanistan. After nearly two decades of war, the American spell has thoroughly been broken, its failures laid bare for every citizen to see, share, like and subscribe. If TV linked together American culture and the military, social media threatens to break it apart[fn:5].

This is how imperial wars come home. Failed imperial wars do not come home by only bringing their guns and training back back[fn:2], they come back by shaking us out of our fugues. The failures of Iraq and Afghanistan prompt Americans to do soul-searching of their society, and what they see now is a society marred by rising inequality, [[https://aelkus.github.io/problem/2020/03/18/collective][leaders asleep at the wheel]], and unresolved racism. American society is deeply adept at amnesia, no true transitional justice has ever been held for Native Americans, and the racial wealth gap between blacks and whites in the US should be self-explanatory. This leads to the rise of "bro" culture, [[https://patrickwyman.substack.com/p/bro-culture-fitness-chivalry-and][a culture where one can escape to a world that seems more meritocratic than the America of today, while talking about how America was already great]]. It leads to the alt-right militias, [[https://www.bellingcat.com/news/2020/05/27/the-boogaloo-movement-is-not-what-you-think/][who are far more devoted to their anti-authority ideology than their racism]][fn:6]. The alt-right militias fight for an America of the past, an America whose sins can be glossed over, atrocities that can be followed by "silence and detachment". Imperial wars come home by bringing more than the toys of war or their scarred soldiers, imperial wars have come by laying bare the indecent form of the American frontier.

* Footnotes

[fn:6] The current militias such as the Boogaloo boys see the current establishment moving towards systems of transitional justice. It's not that they are inherently racist or white supremist (although many of them certainly are), it's that they see attempts at transitional justice as signs that their reality is inherently /wrong/. Their entire identity is premised on this idea of being self-made, that everyone is equal. When the inequities are exposed, we get the anti-authority militias.

[fn:5] This is why the military is so bipartisan, the military is deeply attached to the American empire, and the continuation of the American empire is one thing both parties are keen on.

[fn:4] Such as the Midwest.

[fn:3] Children in cages. Enough said.

[fn:2] Although the surplus weaponry transfers from the Pentagon and the veterans to police pipeline is definitely worthy of further study.

[fn:1] Macaes, History Has Begun, Page 161
