:PROPERTIES:
:ID:       4A009624-59B6-469F-BF79-FBC00E8E002D
:END:
#+SETUPFILE:./hugo_setup.org
#+HUGO_SLUG: archives_introduction_org
#+TITLE: archives-introduction.org

Tags: [[id:F6DEBD6F-7B47-4A1B-9C73-4E32B62E31EA][Problems and Methods - Archival Turn]]

* Outline
  - Archive intro
  - Brief paragraph on each one of the people and themes
    - Themes
      - What gets lost?
      - Who chooses what is recorded?
      - How is an archive organized?
      - Archives in the modern age

    - Shawky
      - Queer voices -> who is left in an out of an archive
    - Diana
      - Palestinians -> palestinaisnms
    -
* Actual

The archive is one of the most seductive objects within our modern world. Originally referring to a location where government records are stored, the emergence of the digital archive, as well as access to archives within the digital space, has pushed the bounaries on what an archive is. The allure of the archive has given birth to what Derrida calls "Archive Fever" -- a mad rush by academics to read both with and against the grain of archives.

In the shadow of academic archive fever, the digital space has produced an analgue: rather than reconstructing the logic for government archives, every person is constructing their own archive. Whether through photos or messages, we have become sentries of our own knowledge and experiences, and in sharing portions of our own archives with one another, we allow each other to engage in archive fever.

With this lens, we analyzed the Digital Forays event held on October 15th with Asunción Molinos Gordo, Mohammad Shawky Hassan, and Diana Allan, moderated by Helga Tawil-Souri. The panel touched on a variety of topics throughout their three projects: the living archive with Asuncion, reenactment of the past to incorporate lost narratives with Shawky, and the transformation of a classical archive into a digital one via video with Allan.

The panel ultimately focuses around a renewed understanding of what the archive is, and the ways in which an archive is problematic. We understood this to be three main topics: the accessibility of an archive, the scope of an archive, and the temporality of an archive.

The accessibility of an archive is one of the more classical archive questions. In answering the questions: who is allowed to see an archive, and what the archive is meant for, we can begin to see the contours of how an archive breaks down. Archives meant for a specific purpose can be challenged and be read in a very different way, and by understanding the logic of how the archive was constructed in the first place, we can begin to break down the archive into its constituiant parts. Diana recreated an archive of refugee experiences, and in so doing, very specifically chose to speak against British propaganda. Although her source material was pulled from a state archive that was geared towards a specific purpose, alteration to the films allows us to view these experiences in a new light.

The scope of an archive, like the accessibility of an archive, is another classical archive question. The questions of "what is worthy of storing in an archive" has plagued scholars for centuries. Not only does this question affect the items that go into an archive, it affects which items may be stored alongside the items, and how items are arranged within an archive. In the wake of the French Revolution, which spearheaded the development of the archival science and "included the conceptualization of the public status of and the stat's responsibilitiers to guard both the nation's heritage" (DiCapua, 100), two principals were established: the relience on provenance and the respect for the primitive order. The reliance on provenance assumes that records have orginated from purposeful organized activity, and that records should be kept within the same order they arrived, allowing them to be reviewed in their totality (this point was repliacted by Zaatari). Respect for the primitive order states that documents should not be reordered, understanding that each series was constructed with reason, and the series order itself is a document. These two principals, in conjunction with the pure decision on what kinds of items go into an archive, means that many voices are left out of archives completely, either based on pure chance or deliberate elision. Shawky's work addressed these points: by recreating classical works and music through queer narratives, he has preserved the series of classical records, in line with archival principals, but also deliberately added the narratives that had been elided out.
