:PROPERTIES:
:ID:       C85D45F7-7AD5-4951-9B51-AB567B7F8114
:END:
#+SETUPFILE:./hugo_setup.org
#+HUGO_SLUG: blumi_the_albania_question_looms_over_the_balkans_again
#+TITLE: Blumi: The Albania Question Looms Over the Balkans Again

Tags: [[id:50FB6225-6F03-42AD-A377-E8DD829BE939][albania]], [[id:67096193-0BA9-4CE6-81A8-6EE477DDC692][balkans]], [[id:EE903E8E-E6F1-4F58-8B1D-CCBE0CD49EBB][papers]]

- https://online.ucpress.edu/currenthistory/article/119/815/95/110413/The-Albanian-Question-Looms-Over-the-Balkans-Again#.X8xg6orxuvM.twitter

Argues that Brussels and Washington have supported elites that are despised and fail to achieve better qualities of life for their constituancies

#+begin_quote
The  consequences  will  likely  prove  destabiliz-ing,  both  locally  and  beyond.  Opposition  to  an  entrenched political elite may take a more violent turn  if  citizens  realize  that  yet  again,  voting  in  elections will not result in real change. That would further expose the clear divergence of strategic in-terests that has arisen among NATO partners dur-ing the Trump era. Without the prospect of nego-tiations  for  EU  membership,  Brussels  risks  losing  influence  in  Albania,  Kosovo,  and  North  Mace-donia. That would give Turkey and Russia greater leverage,  as  outside  powers  once  again  jockey  to  shape the region’s politics.
#+end_quote
