:PROPERTIES:
:ID:       252E5A31-7C9D-4B65-9FAF-CE97AB5EB96A
:END:
#+SETUPFILE:./hugo_setup.org
#+HUGO_SLUG: comprehensive_test_ban_treaty
#+TITLE: comprehensive test ban treaty (CTBT)

Tags: [[id:7C05085A-564D-4186-B4E7-AD9DC612310A][un]]

* US
  #+begin_quote
The Senate’s consent to ratify the CTBT requires the acknowledgement of a central reality: The United States is not going to resume nuclear testing after a 28-year moratorium. The Stockpile Stewardship program is a major success story. Its continued bipartisan support is assured. The nuclear labs have answered the questions that Senators like John Warner (R-VA) and Dick Lugar (R-IN) had at its inception, leading them to conclude that it was premature to vote for ratification in 1999. Twenty years later, we have the answers Senators Warner and Lugar were looking for. If the Nevada test site isn’t going to be shaking Las Vegas again, we might as well bring China, India and Pakistan into the fold. Two decades later, every significant qualm about the CTBT has been answered. The last lingering concern relates to whispers of tests at Russian and Chinese test sites.
  #+end_quote
