:PROPERTIES:
:ID:       E906E9CC-17A7-4207-BB4D-F19AB7EB46CC
:END:
#+SETUPFILE:./hugo_setup.org
#+HUGO_SLUG: e_activity_2
#+TITLE: e-activity-2

Tags: [[id:2CA4ACAD-7B98-4C7E-AA8B-FC2E0ADE676A][conflict and violence]]

In "Violence and History: A Response to Thandika Mkandawire'', Stephen Ellis puts forth the notion that analysis of violence must be grounded in a historical context in order for proper analysis. Starting as a response to THandika Mkandawire, who originally criticized Ellis's work, Ellis deconstructs Mkandawire's theory of an urban/rural divide as the principal driver of violence within Africa. Going beyond this, Ellis pushes violence into a historical background, stating that the context of violence, mediated through symbols and modern habits, requires history to properly understand. While his research is predominantly focused on Liberia and the civil war that occured, his theory is focused on violence as a tool, guided by history, and demands proper historical understanding.

On its face, this argument is a convincing one. Features of modern political systems, such as parliamentary rules, were not willed into existence at a singular point. These features took centuries to develop, and if we treat violence as a single facet of society, we must also look at the development of violence throughout history. While we normally treat violence as an "exceptional" condition, a condition that is reached only under specific circumstances, this leads to treating violence as a unchanging, transtemporal mechanism. This is a moral and legalistic view of violence, which Gilligan asks us to abandon. However, by treating violence as just another tool used in society, we can begin to examine how it develops.

However, it is also easy to see how evaluating violence within a historiographic framework can fall into conceptions of primordialism and essentialism, which formed the basis of Mkandawire's critique. Studying the development of violence with a historical perspective carries the danger of overemphasis of history and de-emphasis of the agency of people. This type of reductionism already exists when describing nationalism, ethnicity, and sectarianism, such as the stress on the Sunni/Shia/Kurd divide in Iraq. While the commonly accepted understanding is that these three sects within Iraq have long held enmity towards one another, leading to the artificial state narrative, scholars such as Fanar Haddad and Sara Pursely have argued that a coherent Sunni identity did not emerge until after 2003. These sectarian identities, like violence, are not transtemporal and static, and were instead shaped by historical circumstances.

The paper is weakest when Ellis draws some parallels between the history of lynching and the symbols of the Liberian civil war. Ellis finds that the history of lynching in the US bears resemblence onto how the most extreme forms of violence during the Liberian civil war were historically motivated. His framework here is conceptually shallow here, most forms of violence can be found to have some amount of historical rooting, as history is largely recorded by the victors. Victors are motivated to justify their own violence through a variety of means, which means that further violence, either in response to past actions or the continuation of past actions, can find quick justifications.

Bibliography
- Stephen Ellis, ‘Violence and History: A Response to Thandika Mkandawire’, The Journal of Modern African Studies, 41.3 (2003), 457–75 <https://doi.org/10.1017/S0022278X03004324>.
- Gilligan, James, ‘Shame: The Emotions and Morality of Violence’, 20
- Fanar Haddad, ‘SECTARIAN RELATIONS BEFORE “SECTARIANIZATION” IN PRE-2003 IRAQ’, in Sectarianization: Mapping the New Politics of the Middle East, ed. by Nader Hashemi and Danny Postel (Oxford ; New York, NY: Oxford University Press, 2017).
- Sara Pursley, Familiar Futures: Time, Selfhood, and Sovereignty in Iraq, Stanford Studies in Middle Eastern and Islamic Societies and Cultures (Stanford, California: Stanford University Press, 2019).


Ellis brings up the history of lynching in order to describe the complexities of violence. Lynching, Ellis states, had several transitional periods, from a mob rule period to a racial oppression period. He states that lynching accomplishes two goals: it is an element of communication that targets and excludes certain groups, and that lynching is a form of violence that exists outside of the state monopoly of violence, even during a stable state. These two factors, Ellis states, is similar to the various acts practiced during the Liberian civil war, which then in turn requires historical understanding. It is here that this framework of applying historical context to violence breaks down, it is fairly trivial to bend any situation that occurs during a civil war to fit Ellis's two goals. Even as Ellis finds the most extreme violence during the Liberian civil were were historically rooted, this framework remains conteputally shallow. Any act of violence can be found to be historically motivated, given that history as recorded is largely a victor's history. Victors are motivated to justify their violence, often times itself in history, rendering Ellis's framework shallow.

Ellis ends by calling for a re-evaluation of the historiography in order to understand the nature of violence. This is largely a convincing argument, for example, recent scholars such as Sara Pursely have called for a renewed interest in the 1959 Personal Status Law in Iraq, which many scholars ascribe to be the cause of the 1963 Ba'thist revolution. While there exists large corpus of data on the law's effects, most analysis of the Personal Status Law devotes only a few sentences[fn:3]. Understanding the historical context the Personal Status Law was written, we can understand the context of Ba'thist violence in greater detail.

- Zizek and subjective and objective violence
  - Only the former is recongized as a objective violence
  - Only secondary violence is observed

* Footnotes

[fn:3] Pursely 176

[fn:2]

[fn:1]
