:PROPERTIES:
:ID:       8EB13E02-5625-4995-9F2D-E0F087F9F849
:END:
#+SETUPFILE:./hugo_setup.org
#+HUGO_SLUG: e_activity_3
#+latex_header: \usepackage[citestyle=verbose-trad2,bibstyle=numeric, hyperref=true,backref=true,maxcitenames=3,url=true,backend=biber,natbib=true,ibidpage=true] {biblatex}
#+latex_header: \addbibresource{~/Dropbox/bib/refs.bib}
#+TITLE: e-activity-3
#+EXCLUDE_TAGS: noexport



Prompt: Where does responsibility for violence suffered by migrants lie?

* Outline                                                          :noexport:
Tags: [[id:2CA4ACAD-7B98-4C7E-AA8B-FC2E0ADE676A][conflict and violence]]
- Split among the continuum from "refugee" to "economic migrant".
- "Segregative biopolitics" as a management technique
- Largely, migrants fall to a few problems, but the root are those responsbile in perpetuating the forms of segregative biopolitics
- Use lebanon as a case study, ahareen: palestians as blurred, syrians as "pure refugees", the foreign workers as pure economic migrant]s
- For "pure refugees", the responsbility lies with the international system that keeps them out, the states that push them to move, and anything that happens in transit
  - Keeping them out: failures to rescure, politican fears of a security stable state (lebanon and fortress europe, etc)
- For "economic migrants", the
- Easy to segregate those directly responsible on the movements of transit
- Refugees as a passive voice is wrong, refugees and history are a two way street
- Article stating that refugees would not exist without the modern state
- Lebanon, neoliberalism's proving ground provides fertile soil for this
- Modern NGO's? What is to be done about Oxfam?
  - Breakdown of segregative biopolitical order exposes chasm in how modern NGO's, which are meant to patch up violence, work
- Effective states vs non-effective ones


* Draft
Migrants suffer a litany of horrors on their path to their ultimate destination. Existing on the bounded continuum, migrants are labeled somewhere between "refugee" and "economic migrant". This dual classification, with significant grey area in between, affords people different rights and treatment along the way. For example, the term refugee carries implies significant loss of agency, but garners international sympathy and affords access to certain institutions. "Economic migrant" garners more mixed reactions, but carries with it an implication of choice and some amount of dignity. Both of these labels have shown to inaccurately describe current migration flows, yet their usage persists in common discourse. The result is the responsibility of violence is attenuated between the actors encountered by the refugees: destination governments, governments of states in transit, and the initial government that caused the migration. However, I argue that the actors with the most responsibility for violence against migrants is not any singular or blocs of states, but rather /any actor that engages in segregative biopolitics against migrants/. This includes not only actors such as the EU or the United States, but also the UN.

This essay aims to explore the status of /al-akharin/, or "the others" in Lebanon as a case study, and its relationship to the refugee-economic migrant continuum. The /akhariin/ are composed of three groups: Palestinians, Syrians, and foreign workers. Lebanon hosts a significant population of Palestinian refugees, whose relatively long term of stay has muddled makes it difficult to cleanly classify them on either pole. Syrians, given the relative recency of the conflict, lean more closely to the refugee end, while foreign workers, imported from Nepal, the Philippines, and other countries, lean further towards the economic migrant end. In addition, Lebanon's political system, carefully balanced through sects that require careful management of biopolitics, presents a country that steadfastly refuses long term settlement of any group, whether they be Palestinian, Syrian, or foriegn workers.

The neologism of "segregative biopolitics" is borrowed from Aslı Iğsız footcite:igsiz_humanism_2018, describing the racialized taxonomy that occurs when evaluation of migrants. This taxonomy on the international level constitutes what Iğsız terms "another terrain of population management", calibrated towards not only the process of migrating /in/, but also the process of deportation and assimilation.

The working terminology of "refugee" will be the one provided by Emma Haddad footcite:haddad_refugee_2001, describing a refugee as "someone that has been forced, in a significant degree, outside the domestic political community indefinitely". The term "economic migrant" will be used as the contrary, describing someone that has *not* been forced, but still outside the domestic political community. Notably, these two definitions leave out the aspect of /influence/. It is commonly assumed that refugees, cut off from their homeland, have lower levels of agency and cannot influence history or their surroundings. Economic migrants are assumed to have "given up" the same agency when making the choice. However, this is hardly the case. Migrants leave a profound impact on the countries they arrive in and contribute to history as a "contribute to History to such an extent that they may be at crucial moments considered a generative force behind" footcite:blumi_ottoman_2013.

If the migrant is taken to have agency and not remain as a meme object of pity, as Blumi describes, then the actor left with the most responsibility for violence incurred is simply the one that prevents the migrant from exercising their agency, namely states and organizations that engage in segregative biopolitics. Migrants who are denied their agency are seen as objects of pity, and the reproduction of this stereotype requires refugees to be passive victims.

The structure of the essay will be the introduction of the concept of segregative biopolitics, the refugee/economic migrant continuum, and a short discussion on Hannah Arendt's people/territory/state trinity. Crawley's identification of categorical fetishism footcite:crawley_refugees_2018 will be used to set the stage for the main argument. The argument is then made that the UN, through the privilaging of refugees and usage of organizations such as the UNWRA that perpetuates the refugee stereotype, and bears equal responsbility to states that enact exclusionary policies. Two main points support the thesis: NGO's and the UN, through the channels of Permanent emergency and delcolonization footcite:duffield_development_2007 override the traditional social constraints. This strips away the identity of people concerned, resulting in the perpetuation of the refugee stereotype. Violence in this essay will be taken to expand beyond physical violence. Mental and temporal violence, such as subjecting migrants to substandard conditions without realistic hope of change is also another form of violence.

Lebanon will then be presented as the case study, going through a brief history of each of the three groups. For Palestinians, their relatively long stay in Lebanon will be used as the basis to analyze them as what Crawley described as refugees that became economic migrants. Saad Hariri's 2017 speech of the census of Palestinian refugees footcite:houssari_first_2017, in a country where an official census has not been taken in decades, will be examined as a starting point. Since a census is key to circumscribing the political terrain, the census of Palestinian refugees is a notable one. In addition, the preamble of the 1990 Lebanese constitution states "no settlement of non-Lebanese in Lebanon", which is understood to refer to Palestinians shows how the Lebanese state degrades and causes violence against the Palestinians. In addition, UNRWA and the Palestinian Red Cresent and their effects of debasement upon the Palestinians footcite:chaaban_socio-economic_nodate are another source of violence.

The Syrian presence in Lebanon will be provided as an example of the refugee status. Their status, having not be formalized into mechanisms of the state yet due to their shorter term presence when compared to the Palestinians, is one of precariousness. However, because the Syrians have not been completely subsumed under the umbrella of UN/NGO/state organizations, their employment opportunities, especially with regards to militant groups, exists in much more of a grey zone. This gives exposes them to different actors who play on the agency of Syrian refugees, which diffuses the responsibility of violence in a different manner.

Finally, the foreign workers of Lebanon, who are the most easily classifible, will be presented. Given the revolving door status of these foreign workers, and the fact that there is exists no umbrella organization, the violence these workers face are diffused between the public, who employs them and cause the violence, and the Lebanese state, which fails to create laws to protect them. Human Rights Watch has documented many abuses against these workers footcite:noauthor_lebanon_2018. The foreign workers under the /kafala/, or sponsership, system are not mere observers as well, they have formed groups such as the Alliance of Deomestic Workers in Lebanon footcite:noauthor_alliance_nodate or the Migrant Domestic Workers Union footcite:noauthor_we_nodate. The inaction of the Lebanese state, including failing to address the problem of discrimination against non-Lebanese individuals footcite:arsan_lebanon_2018 is another form of violence.


* Notes from office hours                                          :noexport:
- Context of the segregative politics
  - Definitely frame the response the response
- Not just the physical, but also structural and temporal violence, there is no realistic path to citizenship for many of the lebanese
  - Define violence early, what we understand violence to mean
    - Define the terms early what the structural and temporal violence
    - Consistency in the way violence is understood
      - Push the limits of the definition of violence

- DDR
  - SSR
  - David Kine - Civil War in Sierra Leona
  - Chris Cramer - Writes about the political economy of conflict and post-conflict reconstruction
    - Labor market reintegration

  - Reconstruction and reintegratino reminder

  - Karen more well versed in biopolitics
    - References and thoughts on it
    - Shoot Hasan email

** Additional notes
   - What was missing in Rwanda and Srebrenica was not evidence of an atrocity, but the willingness to act upon it. As one investigative report on the Rwandan killings noted, ‘Any failure to fully appreciate the genocide stemmed from political, moral, and imaginative weaknesses, not informational ones.’
