:PROPERTIES:
:ID:       DE06E988-C805-48A4-973A-7128C7971835
:END:
#+SETUPFILE:./hugo_setup.org
#+HUGO_SLUG: integrated_ddr_standards
#+TITLE: integrated ddr standards

Tags: [[id:E900796C-250A-474B-9054-C0C109C94A24][ddr]]

- http://un.org.np/node/11787
- https://www.unddr.org/the-iddrs/level-1/
- United Nations. “Disarmament, Demobilization and Reintegration : Report of the Secretary-General,” 2006. https://digitallibrary.un.org/record/571084?ln=en.
- Followed up by the [[id:F1FE4375-6C99-47BA-B77A-D8514DD31790][stockholm initatives in ddr]]

Advises everything from collection of data to ensuring the national ownership of the DDR.


* Specific Definitions

** Disarmament
 Disarmament is the collection, documentation, control and disposal of small arms, ammunition, explosives and light and heavy weapons of combatants and often also of the civilian population. Disarmament also includes the development of responsible arms management programmes.

** Demobilization
 Demobilization is the formal and controlled discharge of active combatants from armed forces or other armed groups. The first stage of demobilization may extend from the processing of individual combatants in temporary centres to the massing of troops in camps designated for this purpose (cantonment sites, encampments, assembly areas or barracks). The second stage of demobilization encompasses the support package provided to the demobilized, which is called reinsertion.

** Reinsertion
 Reinsertion is the assistance offered to ex-combatants during demobilization but prior to the longer-term process of reintegration. Reinsertion is a form of transitional assistance to help cover the basic needs of ex-combatants and their families and can include transitional safety allowances, food, clothes, shelter, medical services, short-term education, training, employment and tools. While reintegration is a long-term, continuous social and economic process of development, reinsertion is a short-term material and/or financial assistance to meet immediate needs, and can last up to one year.
`
** Reintegration
Reintegration is the process by which ex-combatants acquire civilian status and gain sustainable employment and income. Reintegration is essentially a social and economic process with an open timeframe, primarily taking place in communities at the local level. It is part of the general development of a country and a national responsibility, and often necessitates long-term external assistance.
* Lessons Learned
  - DDR has often been conducted in a fractured manner
    - "At best, this has resulted in disjointed programmes with large gaps between the various components. At worst, it has led to disillusioned ex-combatants returning to arms as was the case in Sierra Leone and in Haiti."
  - Narrow focus on short-term security goals has often lead to the exclusion of women and minorities, such as in [[id:A5CACE85-C257-4B0D-93ED-1D1FD8D9BEB5][sierra leone]] and [[id:0F39D232-47FB-4BDF-9AFD-809C65DB7A08][liberia]]
    - [[id:1A7F8EC9-B51F-460B-A078-FCB63DEC29B7][democratic republic of the congo]] and [[id:75596EDC-4243-41A7-A85A-8BC334C2048C][burundi]] failed to account for women
  - DDR cannot be implemented in isolation
  - DDR is contingent on all the political will of parties to the conflict
  - Fragmented approach to DDR within the UN undermines the peace process
  - disarmament and demobilization can be accomplished on a short timespan, reintegration is open ended
  - practionioner based, we must capture all the knowledge previously learned
  - Failure to disarm former combatants and to control weeapons seriously undermines long temr peace
  - Demobilization is multifacted, marks the change of status of a combatant to civilian, requires careful integrated planning, timing, and sequencing
    - Avoid cash benefits for children
      - [[id:0F39D232-47FB-4BDF-9AFD-809C65DB7A08][liberia]], payment of 300 transitional safety net had significant negative impact on children
  - Reintegration is open ended and often handed over other development agencies
    - [[id:A5CACE85-C257-4B0D-93ED-1D1FD8D9BEB5][sierra leone]], UNAMSIL ended in 2005, but UNDP took over reintegration
  - Ongoing conflicts reintegration support can prevent the rerecruitment of children
  - 5 key points of reintegration
    1. Start planning for reintegration ASAP
    2. Develop national capacity
    3. Situate reintegration within a wider recovery strategy
    4. Balance equity and security
    5. Ensure a timely transition from supporiting individuals to supporting communities
  - Reintegration benefits must be tailored based on gender, age, educational equalifications and etc
  - Special consideration for demobilized former faction leaders
  - Funding has been a major problem, disarmament and demobilization are easy to fund, where as reintegration is hard to fund and open ended, long funding cycles
