:PROPERTIES:
:ID:       AD11E1D3-DA4B-4370-95A4-5FD5DB4A3F65
:END:
#+SETUPFILE:./hugo_setup.org
#+HUGO_SLUG: iraq_un_reports
#+TITLE: Iraq UN Reports

Tags: [[id:7C05085A-564D-4186-B4E7-AD9DC612310A][un]], [[id:3D669C14-9C67-43A0-9580-04E5EEB10849][iraq]]

* Visits Table

* 5 August 2004 - S/2004/625
  - Implementation of the non-voting Chief Electoral Officaier and non-voting UN member
  - Kirkuk - Monitored the implementaiton of the CPA in the exercise to identify candidates for the posts of electroal comissions
* 7 March 2005 - S/2005/141
  - Discussed kirkuk as a potential flash point
* 7 June 2005 - S/2005/373
- Stressed "inclusiveness"
  #+begin_quote
In all his discussions, Mr. Qazi has stressed the importance of inclusiveness and achieving a balanced representation in the composition of the Government and in the drafting of the Constitution to ensure that the legitimate interests and concerns of all Iraqis are addressed. Both inside and outside Iraq, my Special Representative and his team met with representatives of Arab Sunni communities, tribes and groups to gain a better understanding of their concerns and intentions with regard to the political process. My Special Representative firmly encouraged them to articulate their views through peaceful participation and dialogue
  #+end_quote
- Possibly conflating "federalism" and "sectarianism"?
#+begin_quote
UNAMI has organized its assistance programme in five distinct areas: facilitation and good offices geared towards promoting inclusiveness and consensusbuilding; institutional support to include material assistance, capacity-building, training and expertise; knowledge-sharing on procedural and substantive subjects, such as the nature of the State, federalism, human rights (including women’s rights), civil service and armed forces; public outreach to include education of media, civil society and communities (
#+end_quote
- minister of finance as focal point for coordination
- discussed returnees into Kirkuk
* 3 March 2006 - S/2006/137
  - Deployed pre-election and post-election field auditors as well as field monitors
* S/2006/706
  - Calls for unity of government and breaking the cycle of violence, but no calls for specific movements such as the notion of sects
* 5 Decembver 2006 - S/2006/945
  - Calls for resolutions over tensions of Kirkuk and de-baathification process
* S/2007/126
  - Recongizes the complexities of Kirkuk and asks that several of the specific issues need to be solved
  - Calls out the issues of a full empowered electoral comission
  - Recongizes that many fled after the bombing of the Al-Askari shrine
  - calls for notions of unity
    #+begin_quote
In these difficult times, Iraqi politicians, religious leaders, tribal elders and influential members of civil society must not lose sight of the fundamental goal of preserving Iraq’s national unity. They must work towards settling their differences peacefully and protecting the human dignity of all Iraqis, irrespective of their creed and ethnicity...Ultimately, the Iraqi people and their leaders face a fundamental choice, between seeking a negotiated political settlement or drawing further into the abyss of sectarian conflict
    #+end_quote
* S/2007/330
  - Recongizes the issues with Kirkuk and the fact that there is not an effective electoral registry
  -
* S/2007/608
  - Special represenitive visited Kirkuk
  #+begin_quote
The Special Representative paid close attention to developments relating to the implementation of Article 140 and visited the Kurdistan region on two occasions, from 10 to 12 July and from 16 to 18 September, to consult with senior officials of the Kurdistan regional government.
  #+end_quote
  - Notes the fall in violence
  #+begin_quote
There is now an opportunity that should not be missed. September witnessed the lowest number of Iraqi casualties for the year. The decrease in violence resulting from the ceasefire by the Mahdi Army and the Sunni insurgent allegiance against Al-Qaida holds significant political potential as well.
  #+end_quote
* S/2008/19
  - Ashraf Qazi leaves
  - Failure to implement Article 140, although engagements with the UN:
    #+begin_quote
Perhaps the most encouraging development in Iraq was the readiness recently shown by the top leadership in Baghdad and Arbil to begin to work cooperatively among themselves and with my Special Representative to ensure that tensions relating to the lapse of the deadline in article 140 did not lead to further violence. I now call upon those leaders and their constituents to continue to move along this path with the same statesmanship and spirit of cooperation they have displayed during the most recent discussions. In particular, I invite them to take advantage of the agreed-upon six-month period and the offer of technical assistance from UNAMI and to make progress in deciding the future of some of the disputed territories.
    #+end_quote
* 28 July 2008 - S/2008/495
- No mention of "sectarian"
* 6 Nov 2008 - S/2008/688
  - Meetings with the individual minority groups
    #+begin_quote
Christian, Yezidi, Shebek and Sabean Mandean communities to reassure them of the continued engagement of the United Nations on the issue of minority representation.
    #+end_quote
    - Established an office in Kirkuk
** Observations
   - Recongizes the peace is fragile, calls for unity and reconciliation
     #+begin_quote
I therefore appeal to Iraq’s diverse communities and their political leaders to continue to work with one another in a spirit of dialogue and grand compromise in a manner that reinforces the overall national interest.
     #+end_quote
   - met with grand ayatollahs
   #+begin_quote
During the reporting period he visited Najaf, where he met with several political and religious leaders, including Grand Ayatollah Ali al-Sistani and Grand Ayatollah Fayyad. Grand Ayatollah Ali al-Sistani expressed his appreciation for the work of the United Nations in Iraq and, in particular, the Organization’s efforts in facilitating the negotiations on the provincial election law. My Special Representative also made a visit to Ramadi, highlighting the commitment of the United Nations to the expansion of its presence in Al-Anbar Governorate and the delivery of programmes on the ground throughout Iraq.
   #+end_quote
* S/2009/102
  - sets up a committee to discuss kirkuk
    #+begin_quote
In this connection, the mission has been working with a parliamentary committee set up according to article 23 of the provincial elections law. The committee was tasked by the Council of Representatives to (a) determine a power-sharing formula before provincial elections are held in the Kirkuk Governorate; (b) assess the issue of property disputes before and after 9 April 2003; and (c) c
    #+end_quote
  - Another call for unity, notes about kirkuk
    #+begin_quote
In the coming months, attention is likely to shift towards the issue of disputed internal boundaries and the status of Kirkuk. The groundwork being undertaken by UNAMI with key interlocutors in Baghdad and in the disputed areas remains a priority for the mission. The United Nations is committed to playing an impartial and neutral role towards building confidence and trust among the parties concerned, promoting dialogue and helping to forge a consensus.
    #+end_quote
* S/2009/284
  - Continued discussion of the article 140 committee
  #+begin_quote
Subsequent briefings took place with the relevant parliamentary committees, including the article 23 committee, the article 140 committee and the Constitutional Review Committee.
  #+end_quote
  - Ignores the overt toned nature of a sectarian-based federalism
    #+begin_quote
Nevertheless, many important challenges remain, and further progress is needed in the coming months to ensure that the gains made so far can be sustained. As I have said in my previous reports, national reconciliation remains the main priority in Iraq. In particular, the resolution of key issues, including federalism, the sharing of natural resources and disputed internal boundaries, could serve as a means to achieving lasting peace. Further progress on these complex issues will be possible only if Iraqi leaders come together in a spirit of national unity and adopt muchneeded constitutional and legislative measures in the political, electoral, economic and social fields.
    #+end_quote
  - acknolwedges rising tensions, but attempts to reconcile this through a "spoils of war" method, by linking rising tensions to disputed boundaries
    #+begin_quote
I note with concern rising tensions in several areas, particularly in Ninawa, Kirkuk and Diyala. While I welcome the recent effort to organize joint patrols between the Iraqi Security Forces and the Peshmerga in some disputed areas, much more needs to be done to stabilize the situation. I urge national and local leaders to endeavour to ease tensions and work towards resolving the underlying causes. In this regard, I support the efforts of my Special Representative and UNAMI to facilitate a political dialogue and assist the parties in finding mutually acceptable solutions. In particular, the Mission’s report on the disputed internal boundaries of Iraq could serve as a useful starting point for constructive dialogue
    #+end_quote
* S/2009/393
  - Calls for an end to provactive statements from Kurdistan regional gov and the Iraqi gov as a way of toning down tensions
    - this is good? although ignores the ways that these tensions
* S/2009/585
   - Another call for elections as reconcilation
     #+begin_quote
Since 2003, with United Nations assistance, Iraq has managed to hold three successful elections and a national referendum, generally considered credible and broadly participatory. The peaceful conduct of provincial elections and Kurdistan Regional Government elections earlier in 2009, underscores this remarkable achievement. I firmly believe that the forthcoming national election planned for January 2010 represents a historic opportunity for Iraq and a crucial step forward for national reconciliation
     #+end_quote
- Continued calls for engagement of [[id:DEA58D28-C6BA-433A-9AC3-4C2300A4F6B1][kirkuk]]
  #+begin_quote
In order to bring political stability and lasting peace to the country, it is essential that the Federal Government in Baghdad and the leadership of the Iraqi Kurdistan region strive to resolve their differences through meaningful dialogue. Continuing disagreements, in particular with respect to disputed internal boundaries and the sharing of the natural resources, will hinder political progress at the national level.
  #+end_quote
- First call for neighbors non-interference ([[id:5E8A9793-6DE6-4E2C-A33B-D85714A3C06C][iran]]?)
#+begin_quote
The normalization of Iraq’s relations with its neighbours is important for regional stability. Cooperation on a range of issues of mutual concern, including trade, energy, border security and refugees, will be vital to this end. Regional cooperation is a two-way process. Both Iraq and its neighbours will need to engage each other and demonstrate their willingness to listen to each other’s concerns. I also call upon all Member States, and in particular Iraq’s neighbours, to respect Iraq’s sovereignty and to adhere to the principle of non-interference, a fundamental tenet of the Charter of the United Nations.
#+end_quote
* S/2010/76
  - Encouraged by workable solutions, but the solutions are ones that break the impasse via divvying up resources
    #+begin_quote
Despite the lengthy negotiations on the Election Law, I was encouraged by the determination and dedication of Iraqi leaders to find workable solutions and compromises. I would like to commend all those involved who worked to finalize the law and keep the electoral timetable on track. In the same spirit, I appeal to all political blocs and leaders to demonstrate true statesmanship during the election campaign, use the mechanisms in place to submit formal complaints, and abide by the final election results once they are certified by the Federal Supreme Court.
    #+end_quote
* S/2010/206
- Welcomes the nomination of al-Maliki, zero mention of the rulings by judge medhat
#+begin_quote
I commend all political blocs and their leaders for engaging in a collective process and reaching agreements that appear to have ended the deadlock in the government formation process. The breakthrough represents a major milestone in democratic progress for Iraq and should pave the way for the first peaceful transition between elected governments under full Iraqi sovereignty. I congratulate President Talabani on his re-election, as well as Mr. Al-Nujaifi on his election as Speaker and Messrs. Qusai al-Suhail and Aref Tayfour, on their election as Deputy Speakers. I also welcome the nomination of Mr. al-Maliki as Prime Ministerdesignate.
#+end_quote
* S/2010/240
- Highlights the high level task force between Arab/Kurdish issues
re  #+begin_quote
The high-level task force, a mechanism aimed at fostering dialogue on ArabKurdish relations, continues to focus on resolving outstanding issues concerning areas of mutual interest through the development of confidence-building measures. In its meeting on 7 February, the task force agreed to prioritize the issues of property disputes, detainees and language rights in schools. In particular, it called upon political parties to vacate occupied schools in Kirkuk so that they may be returned to public use.
  #+end_quote
* S/2010/406
- Facilitates an Arab-Kurdish dialogue
  #+begin_quote
In a renewed effort to normalize Arab-Kurdish relations in the north, UNAMI supported a government-initiated dialogue process aimed at ending the boycott of the Ninewa Provincial Council and facilitated two meetings between the Ninewa Fraternal list and the Hadba list on 3 April and 15 May, respectively. The discussions focused on security-related issues and the transfer of detainees from Ninewa (currently held in the Kurdistan region), as well as power-sharing with regard to senior posts in the Ninewa Provincial Council.
  #+end_quote
- Mentions of minorities
#+begin_quote
The Mission also facilitated two further meetings of the newly established Committee on Ethnic and Religious Communities under the Ninewa dialogue process. Participants included representatives of the Christian, Shabak, Turkoman and Yezidi communities, as well as representatives of the Ninewa administration, KRG and the Government of Iraq.
#+end_quote
- Again calls for national reconciliation and more dialogue
  #+begin_quote
In particular, promoting dialogue and encouraging compromise in disputed areas will greatly contribute to the country’s stability. In this context, I am encouraged by the progress being made in talks assisted by UNAMI to end the impasse over the boycott of the Ninewa Provincial Council by Kurdish parties. An agreement would contribute significantly to easing tensions in the disputed territories and restore confidence insofar as resolving Arab-Kurdish issues at the national level.
  #+end_quote
