:PROPERTIES:
:ID:       D44E1843-9806-4445-835C-4700A1F5B535
:END:
#+SETUPFILE:./hugo_setup.org
#+HUGO_SLUG: post_ottoman_iraq_egypt_irrigation_essay_draft
#+EXCLUDE_TAGS: noexport
#+LATEX_CLASS: koma-article
#+latex_header: \usepackage[citestyle=verbose-trad2,bibstyle=numeric, hyperref=true,backref=true,maxcitenames=3,url=true,backend=biber,natbib=true,ibidpage=true] {biblatex}
#+latex_header: \addbibresource{~/Dropbox/bib/refs.bib}
#+TITLE: Irrigation in Egypt/Iraq Paper

* Noexport :noexport:
Tags: [[id:A438ACD2-2C1E-40EB-9502-74E5B69EA9FF][Post-Ottoman Near East]], [[id:29FA0621-3C54-482F-8CFC-72CAE922DE11][Paper Topics for Post Ottoman Near East]], [[id:DB155060-FE5B-4E83-BEBF-522C57CE7310][post-ottoman iraq/egypt irrigation essay research]], [[id:0DEB2388-5061-4C4E-B384-A8C1F666089D][post-ottoman iraq/egypt irrigation paper proposal]]


** Abstract
   The opening of the Aswan Low Dam in 1902, as well as the Aswan High Dam in 1960 in Egypt has drawn significant scholarship in modernization theory and environmental history. Notions of modernity within Egyptian society were debated about within the context of both the Low and High dams. Yet curiously little is written about the dams of Iraq, specifically the Hindiya Barrage, opened in 1913, and the Kut Barrage, opened in 1939. These two Iraqi dams provide unique lenses against the scholarship of the Aswan dams within the notions of modernity and development, as the Low Dam and the Hindiya Barrage were constructed under the Ottoman Empire, while the High Dam and the Kut Barrage were constructed after both nations had technically achieved indpendence from the British state. This article examines the technical background, environmental impact, and the modernization trends that took hold in both Egypt and Iraq during these periods.

** Introduction
   The first Prime Minister of India, Jawaharlal Nehru, famously state that dams were the new temples of modern India cite:biswas_development_2001.
   - Dams are important signs of modernity
   - cite:biswas_development_2001 talks about the importance of water control and assured water availablity
   - Developing nations face very different challenges of water resources than developed ones
     1) Developed nations exist in temperate climates with consistent yearly water
     2) Many developing nations do not
   - Large trends can be identitifed post-1950 and post-1975 for "modern" history of dams
     - 1950 had an urgency
     - 1975 had a birth of environmental impact assestments
   - This article looks at an earlier trends and the breaks between the ottoman empire of dams and the post ottoman pre-1950's ones
     - Developmental style cited in cite:igsiz_humanism_2018
   - Introduce the Aswan Low Dam, the Aswan High Dam, the Hindiya Barrage, and the Kut Barrage.


   Massive infrastructure projects within the 20th century have typically been harnessed for nationalistic purposes. While most analysis focuses on the nationlism generating certain types of public works projects, projects constructed under colonial governments and then semi-independent governments reflect much upon the status of a state as well. Palestine's electrification project, placed under the administration of a Russian Zionist cite:waste_seige, tells us much about the status of the British government, and their views towards the territory and people of Palestine. The far more recent Beirut trash riots, which have continued to simmer ever since 2015, have become a focal point for protestors and opposition groups as a sign of government incompetence. Along these same lines, massive dams, beginning with the Aswan Low Dam in Egypt and the Hindiya barrage and through the era of dams modeled after the Tenesse Valley Authority offer another form of looking at the nationalist rhetoric. These irrigation projects, which often came alongside ideals of a "moderized" state, both shaped and were shaped by the kaleidoscope of actors, from the British colonial powers in Egypt, to the Young Turks, to the newly created "independent" states, which sought to clear a certain bar to be considered a "modern" nation.

   Egypt, in particular, repsents two sections. The construction of the Aswan Low Dam is a particular reflection of primordialist perceptions by the British, but also born out of the inherent processeses of de-Ottomanization that occured near the turn of the 19th century. The Aswan High Dam, with its construction coming only three years after the nationalization of the Suez, reflects the power of American influences and follows the trend of legimitizing Nasserism by tying it to state infrastructure.

   Iraq also respresents two distinct periods. The construction of the Hindiya Barrage by William Willcocks, the same engineering who constructed the Aswan Low Dam, marked the ascendence of the Young Turk policy of public infrastructure of a top-down modernization process. The Kut Barrage, with provided for the later construction of the Shatt al-Gharraf canal, would be the foundations and birth of the Dujayla land reform project, a heavily American influenced projects directed with the help of UN institutions.

   The Aswan Low Dam and the Hindiya Barrage share more than just their creator, they were constructed with particular primordialist views. In particular, both dams were percieved as a "gift" towards the inhabitans of Egypt and Iraq, and seen to follow a series of "great works" extending back to the Pharonic Era and the Bablonyians. Particularly, the Philae temple would dictate features of the Aswan Low Dam, and Willock's conceptions of "Eden" within Mesopotamia would encourage him to take on the Hindiya project. With both technocratic reasons and religious influences, the construction of Willcock's dams explains the lack of foresight on later problems caused by the Aswan Low Dam.

   Both the Aswan High Dam and the Kut Barrage were both constructed under states with relatively young governments, with both governments utilizing the dams for legitimacy. Secondary effects of the construction of both reflected a conceptual "maturation" of the state, with the Aswan High Dam erasing Nubian legacies of the past and delinating a future, and the Kut Barrage's connections to the Dujayla Land Project premised along a distinctive "American self-sufficiency" model.
** Current Literature and Discussions
*** Aswan Low Dam
    While greater modern trends following the 1970's have typically painted the High Aswan Dam in a negative light due to its environmental impacts, it is noted cite:cook_engineering_nodate that the Low Aswan Dam is rarely discussed. However, the dams of Iraq face even less discussion on a general basis, although they both present important notes for the shifts in thinking about state structure and modernity in Iraq.

    The Aswan Low Dam provided a watershed moment for development. Constructed between 1899 and 1902 and designed by Sir William Willcocks, it was intended to manage the seasonal flooding of the Nile. Notably, the desire to increase cotton production in Egypt was a primary driver of the construction cite:noauthor_power_1913. Foreign import bans of cotton, alongside massive foreign captial and financial investment made the Egyptian cotton economy "developed to a high lvel of perfection, but practically no industrialization" cite:hansen_egypt_1975.

    Although originally successful, demand for additional water caused the Aswan Low Dam to be raised by 5 meters in 1910-1912, and another 9 meters was added between 1930-1933. Willcocks would later then critque the raisings of the dam in 1919 stating that the insufficient water supply would later cause problems cite:cook_engineering_nodate.

    Concerns about the temple of Philae inherently imposed limitations on the height of the dam. Reaching a solution to keep the temple partially submerged throughout the year, the subsequent raisings of the Aswan Low Dam caused the temple to be continually submerged throughout the year.

    As Cook notes, the changes in soil quality predicted by Willcocks pans out, requiring more abundant uses of fertilzer across the Nile. While Cook argues that the failure to foresee requires that would later lead to the raising of the dam and the construction of the Aswan High Dam is a symbol of orientalist views of constructions, it must be noted that large-scale environmental assessments did not become popularized until 1975. Such critiques of the Aswan Low Dam also fail to consider the environmental necessities in favor of focusing on the particular historiographies. A 2005 Aquastat survey from the United Nations found that while the average African nation experiences 678 mm of rainfall per year, Egypt remains the driest country, with 51 mm. Even within Egypt massive disparaties exist, ranging from 200 mm of maximum annual rainfall within the northern coastal region to a near zero minimum in the South, where both Aswan dams are located.

  All environmental impact assesements are invariably predictions, whose conclusions firmly remain hypostheses cite:biswas_dams_2004. Notably, EIAs fail to properly identify or assess nearly 40-50% of the impacts cite:tortajada_impacts_2012.

*** Hindiya Barrage
    In 1875, Midhat Pasha, the Vali of Baghdad, decided to close the Saklawia Canal on account of its gradual decay to become unavigable cite:great_britain_iraq_2014. However, as a result of its closing, approximately 750 cubic meters of water per second flooded into the main Euphrates river, exasterbating the seasonal floods from March to May. Further downstream, where the Euphrates splits into two branches, the Hindiya and Hilla, began to experience sentiment deposit issues. As the eastern-facing Hilla branch lay on higher ground than the western-facing Hindiya branch, extra water diverted from the Saklawia Canal caused additional sentiment deposit at the river juncture, threatening to clog the Hilla branch and rendering it unsuable. As this area was fertile ground for date palms cite:money_hindiya_1917, the Ottoman Government decided to build a rubble dam across the Hindiya branch in order to divert more waterflow towards the Hilla branch. However, in 1908, the state of the rubble dam had decayed to the point where the Ottoman government solicited outside advice.

    Flush off of his success in the Aswan Low Dam, William Willcocks was hired in light of the Young Turk large public work programms cite:money_hindiya_1917. Utilizing the staff he built during his years in Egypt, Willcocks constructed a new Hindiya barrage, creating two artificial lakes for the excess water: lake Habbaniya and Lake Abu Dilis. The new Hindiya barrage stood further upstream with a locking mechanism, as well as creating two artifical canals in its wake. Notably, once construction was complete, the engineers wanted to remove the old rubble Hindiya barrage, only to hear objections from the Arabs, who stated that "goods have always been unloaded at the barrage and transported overland, so why should they not continue to do so" cite:money_hindiya_1917.

    Evaluations of the Hindiya barrage paint it in an exceedingly glowing light, similar to the evaluations of the Aswan Low Dam. Royal Naval handbooks claim the Hindiya barrage is the "first great modern work" within Iraq cite:great_britain_iraq_2014 pg 434, placing it alongside the Kut bararge and the Diyala weir. Notably, discussions of ruins and bibical records lie in the descriptions of Hindiya barrage. Naval notebooks describe the ruins of Bablyon and orientalist tropes, such as notions of "Lakhmid frontier tribesmen" and "the sedentary people of the Euphrates" cite:great_britain_iraq_2014. These ideas with very little basis are extrapolated to chart out the basis of dry canals.
    - Talk about how the Hindiya barrage eliminated malaria near it (iraq, committee of officials)?

*** Primordialist strains within the Hindiya barrage and Aswan Low Dam
    The obsession with rooting canals, structures, and concerns about history, combined with a narrative around modernizing and "restoring" a formerly glorious cilvization reflects the primordialist trends the British engaged with.  While Willcocks himself considers the debate fairly proposterous in light of the dam itself, he mentions "Philae Temple, dedicated to Venus, will, like Venus herself, rise annually out of the water". Even Wiston Churchill "expressed the sentiments of the public on the lowering of the [Aswan Low] dam to save the Philae temple from immersion" cite:willcocks_assuan_1904.

    In a later lecture at the Khedivial geographical society dedicated to reviewing the Aswan Low Dam, Willcocks has no hesitation in mixing historical references alongside his technical work. He repeatedly cites the importance of his work with irrigation regulators in conjunction with historical references about Joseph's arrival in Egypt cite:willcocks_assuan_1904. A sizeable chunk of this lecture is dedicated to a recollection of history around Joseph, Egyptian pharaos, and Theban kings, before returning to abruptly lurching back to statistics about the cultivable area surrounding Lake Morris. Curiously, the book itself spends little time dwelling on the /current/ residents of the Aswan Low Dam or of Lake Moeris.

    Why did the British public, all the way up a member of parliment, express concern about an Egyptian temple thousands of miles away, built as part of an irrigation project meant to maximize the output of Egyptian cotton? Why did Willcocks flit between history and statistics within his lecture? Why are references to the current inhabitants around both the Aswan Low Dam and the Hindiya Barrage either not described at all, or described with crude generalizations? The fundalmental understanding of both Egypt and Iraq at this time are rooted in conceptions of primordialism. While primordialism itself is generally used as a pejorative today, primordialism for the British can be understood to be a powerful romantiziation of a civilization's early period.

    For Egypt, the temple of Philae is a rallying point for British primordialism, since it is assumed that the Egyptians in the early 1900's are derivatives of the ancient pharonic civilizations. From this we can see that the lack of references to the Egyptians inhabiting the areas around the Aswan Low Dam are simply fait accompli, and require no consideration. Willcocks himself never denies the necessity of the preservation of the Philae temple, he merely takes offense at the idea that he had not constructed an adaequete presevation mechanism vis-a-vis a lower dam height. If the Egyptian past is set in stone as a pharonic civilization, the role of the British is to birth a future via statistics and development projects. From the British perspective, the Egyptians were not worth mentioning because they had no agency, as they existed merely as a line between the two dots of pharonic history and British guided techno-politics.

    This same logic is clear in the Hindiya barrage. The cite:great_britain_iraq_2014 dives into meticious detail about the flow of water, but the same granularity is not applied towards the people. Rather, inhabitants around the Hindiya barrage are described in crude terms that derive from their past as percieved by the British. The term of "first great modern work" in describing the Hindiya barrage is rooted in a conception of the existance of past great works seen to be constructed by the Bablyonians. These descriptions do more than boast about the feats of engineering performed by the British, in describing British achievements as modern works, the British placed themselves rhetorically as the continuation of a Bablonyian engineering legacy.

   - Talk about Willcock's From the Garden of Eden to the Valley of Jordan

    A natural effect of placing these works in the crux of history is a veneration of the self. In the case of the Aswan Low Dam and the Hindiya Barrage, the rhetoric adopted places great emphasis on the value of these works, and the generosity of the British in making it possible.

    The obsession with history and alignment of British engineering in the timeline of Pharonic and Bablonyian history extends beyond simple rhetoric or arguments about archoloegical presevation. The sidelining and devaluation of the customs of the local inhabitans lead to multiple diaseters. cite:mitchell_rule_2002 notes that the construction of the Aswan Low Dam had constrained the flow of the Nile, leaving only one-fifth of its former size plains naturally fertizled via silt deposits. As a result, the remaining four-fifth required fertiziler, with 80 percent of the Egyptian supply controlled by an international cartel. The 1942 food shortage was directly caused by this realignment to using fertilizer, as fertiziler supplies became constrained when war broke out, inducing large numbers of causalities due to food supplies and a malaria epidemic.

    - Hindiya barrage lead to both tax reforms, proliferation of taxation, etc
    -


*** 1950 TVA
    - Modernization along american lines
      - TVA
      - Egypt's "pittsburgh"
*** Aswan High Dam
    Dams within Egypt took on a strict political light following 1956. The natinoalization of the Suez Canal, which was stated for the purposes of replacing World Bank loans for the construction of dams cite:reynolds_city_2017, signaled a shift towards a more decisive, post-colonial drive towards industrialization.
    The Aswan High Dam was one of the first major projects. First proposed by Gamal Abdul Nasser and born out of Cold War dynamics, the literature surrounding the Aswan High Dam is invariably tainted with politcal motives. Orginally due to be funded by the United States, Nasser's alliance with India in forming the non-aligned moved caused the United States to withdraw funding, prompting the Soviet Union to step in in 1959. This has politicized discussions around the Aswan High Dam, to a point where there are significant communities around anti-dam and pro-dam developments.

    Yoav DiCapua describes Nasserism and it's associoated projects as having "a constant need for public demonstration of its achievements. It was exhibitionist" cite:di-capua_gatekeepers_2009. In line with this, not only was the lake created by the dam named after Nasser, the Aswan High Dam also aimed to acheive a massive set of goals: from "full control of the Nile south of the Aswan", to "generalization of cheap and clean hydroelectric power", along with an intention of changing the then-current system of basin irrigation, which limited agriculture to one crop a year, to perinnial irrigation, allowing for two crops a year cite:abu-zeid_egypts_1997. The famed singer Abdel Halim Hafez composed a song called "The High Dam", which was broadcasted across Egypt on state-run channels cite:reynolds_city_2017. The complete absorption of the Aswan High Dam into popular culture simultaneously legimatized the Egyptian regime, even as the dam was financed and designed by the Soviet Union. The creation of Lake Nasser provides a defacto boundary between Egypt and Sudan, both physically and metaphorically representing a break from the Anglo-English condomimum over Sudan.

Furthermore, the creation of the High Dam submerged Nubian villages that provided inspiration for the Egyptian archietct Hassan Fathy. The replaced villages constructed by Fathy were built in

    Notably, after the construction of the dam, multiple American journalists published articles critizing the dam for theoretical adverse impacts on the areas surrounding it cite:biswas_development_2001, futhering entrenching the dam's reputation as a Cold War battleground. Although even as the great powers discourse around the dam revolved along Cold War lines, the American impact on the dam was significant. The Tennesse Valley Authority had become a model to be emulated following 1950 cite:tortajada_impacts_2012, and the chief administrator of the Aswan High Dam, Ibrahim Salem, supposedly stated that he wanted the city of Aswan, which borders the dam, to be a "Pittsburgh of Egypt" cite:reynolds_city_2017.


    This type of discourse marks a specific notion, that the concept of "Pittsburgh"or "the Tennesse Valley Authority" could be packaged and easily deployed as a modernizing force across the world. However, as Mitchell as argued, these types of modernization often overlook significant problems within the host country, leading to disasterous results.

    The Aswan high dam lead to significant impacts, such as the depletion of fisheries in the mediterrean, even further usage of the

    - Importing of american style developments
    - Offloading the costs for the peasnts


**** They considered all these things and modeled after america and american lead development, but the failures were due to the lack of base that was already built up in america, transportation and packaging of "modernity" meant that some things were overlooked.

*** Kut barrage

    Maturation under the Iraqi state fell along similar lines as well. The Kut barrage, with construction beginning in 1934 and finishing in 1939, straddled both ends of World War 2. The Kut barrage would mostly have to wait until after the war to show its secondary effects, particularly the Shatt al-Gharraf canal and the Dujayla land project. While the work of Sara Pursely identifies the Dujayla land project as the birth of a particular "American-influenced" moderinziation model, the Kut barrage itself was a source of legimaization for King Ghazi, and represneted ideas of self-determination for the Iraqi state. While specific features of the Dujayla land project would be molded by UN institutions with heavy American influence, the notions of "self sufficiency" along the Tigris began with the Kut barrage and not the Dujayla project.

    Originally proposed by William Willcocks during the construction of the Hindiya Barrage, the Kut barrage remains the oldest continunally functioning barrage along a main river in Iraq cite:abdullah_water_nodate-1. Meant to regulate the Shatt al-Gharraf canal that links the Tigris to the Euphrates, the Iraqi government wished to irrigate the land surrounding al-Gharraf.

    In many ways, the opening of the Kut Barrage is a front runner to Nasser's legitamacy via the Aswan High Dam. DiCapua describes Nasserism as "a question for a kind of dignity that formed the inner meaning of the word /independence/" cite:di-capua_gatekeepers_2009. Like Aswan High Dam, the Kut barrage was used in two ways: for legitmacy of a young government and to display a type of self sufficency.

    Notably, the opening of the Kut Barrage was the last even King Ghazi of Iraq attended before his death cite:noauthor_king_nodate. Donning a British style uniform and speaking in front of dozens of young children and soldiers, Ghazi spoke about the interest his father held. This event, which was mirrored over over eighty years later with President Barham Salih's visit to the Kut Barrage, speaks to the value of the Kut Barrage. With the revival al-Gharraf canal described as "identical to the course of the main Tigris channel during the Islamic Era more than 1,000 years ago" cite:arab_world_66, the Kut Barrage's existance simultaneously held the notion of the returning into a once-great past. This is unsurprising, as the Kut Barrage was conceived in the same line of thinking as the Hindiya barrage.

    What differentiates the Kut Barrage from the Hindiya Barrage was the fruits of the dams. The Hindiya Barrage succeeded by replacing a dysfunctional, pre-existing dam, while the Kut Barrage attempted to chart a completely new path. The notion of irrigation along the Shatt al-Gharraf were new, despite dreams of "Eden" existing alongside these rivers. The failure of the Dujayla Land Reform project, which held significant problems with salination, land reform, and social features cite:pursley_familiar_2019-1, had its birth in the Kut Barrage.

    To see the connection, the birth of the Kut Barrge began with William Willcocks, but the 1933 Law Governing the Rights and Duties of Cultivators. Previously, a patchwork of Ottoman-era land laws divided land types into three different classifications, mostly held within the hands of the tribal sheikhs and urban landlords. However, following the 1933 Law, land ownership was extended to irrigation pump owners in the case of default by the land cultivators cite:kiyotaki_ottoman_2019. In addition, the "law granted pump owners, lazma [deed] holders, and leaseholders full rights over decisions relating to production, including the choice of crops, choice of seeds (kinds and hybrids), water supply, harvesting, marketing, as well as the hiring of outside labor" cite:haj_making_1997. This meant that, once the Kut Barrage, "the showpiece of the government’s agricultural and irrigation effort" (Kamil Mahadi quoted in Pursely), was finished and the Shatt al-Gharraf irrigated, the subsequent pump owners, who were mostly wealthy and urban cite:kiyotaki_ottoman_2019, along the Shatt al-Gharraf would hold significant power over the peasants fo the newly irrigated land, exasterbating the urban/rural divide and pushing towards free market ideas.


*** Conclusions
    Dams provide a dearth of knowledge, and allow us to reflect on the changing circumstances. Due to massive capital needs for construction, the circumstances and debates around dams tells us much about nationalism and the state of ruling government from a top down perspective. The secondary effects of dams, hand-in-hand with the secondary effects of a massive capital injection, shows us how these ideas are reflected on the ground, and provides a testing ground for the durability of nationalism.

    The secondary effects of dams are not yet well studied within a social context, mostly due to the fact that environmental impact assessments were not carried out until the Tokyo meeting of 1970 cite:biswas_development_2001. Addtionally, these effects are almost completely studied within a economic or environmental frame, and not a social or historical one. The development of the Aswan Low Dam and the Hindiya Barrage, the two "great works" of irrigation that occured at the turn of the century, shows us the devastating effects of reshaping local lives without sufficiently understanding the customs of the local inhabitants. The Aswan High Dam and the Kut Barrage shows us how urban development and rural development, when melded with desires of the government to prove legitmacy have exasterbated rural/urban divides and take on symbolic roles of breaking with the past.


*** Aswan High Dam, Kut Barrage, Salination, Schiosmoatisis.
    - Pursely describes the dujayla land project in the exclusion of the rural to the urban
    - The specifics of dujayla was influenced by american technocrats
    - But the specifics of the Kut barrage were drafted following the /Law Governing the Rights and Duties of Cultivators/
      - The law specified that ownership came with certain rights
      - Decentralized farm ownership, the conception of "idealistic self-ownership" was because it removed the duties of land ownership away from the skheikhs and to the peasants.

**** Self determination
***** Egyptians being proud of the dam
***** Nasser reviving primordialist identities
***** Nasserism's exhibionist tendencies
***** Rewriting history as an allegory for modern identities
**** American technocratic leadership
**** Foreign dominated Iraqi developmental borad
**** Svoiet epxertise in the high aswan dam
**** Nationalism and free market ideas
     - Aswan Low Dam was free market for the egyptian cotton
       - Influenced by primoridalism
     - Aswan High Dam was free market for crop ideas
       - Influenced by american TVA technocrats
     - Hindiya barrage was driven by agricultural needs
       - again primordialist
         - search for eden, etc
     - Kut Barrage was driven by free market and legitimized the government
       - exasterbated the rural/urban divide
         - aimed at increasing free market

*** Conclusions
    - Conceptions of the primordial past signifies what?
    - Primoridalist -> nationalistic populism?
    - Conceptions of dieases singifies what?
    - What does the change actually mean?
      - American ascendance?
      - New types of nationalism?
      - Humanism in ruins?
      - Constructivst ideaologies?
      -

**** Intro
     - Dams tell us a lot
     - Specifically, the secondary effects of dams tells us a lot
       - Moquitos, diease, malaria
       - free market economics
       - nationalism and a state desire for legitimacy

**** Discussions
     - Aswan Low Dam and Hindiya Barrage were both born out of primordialist conceptions, but different levels
       - Aswan Low Dam didn't take into account the local needs
         - malaria, tragedy ensued
         - deottoman
       - Hindiya barrage did take into account local needs
         - malaria prevented, highly functional
     - Aswan High Dam + development of the city of Aswan and Kut Barrage/Dujayla project tells us how states achieved legitmacy via public works projects
       - both post ottoman
       - both highly coveted and covered
       - exasterbating the urban/rural divide
       - both market symbolic breaks from the past, either with new reformation models, new cities, or massive new projects
       - Aswan high dam predicted to have significant problems with Schistosomiasis, didn't
       - Dujayla land project predicted to have signifciant problems with salination, and it did

**** Conclusions
     Dams tell us a lot, secondary effects of dams are important and most of all hard to predict.


* Outline :noexport:
   - Dams tell us a lot
   - Aswan Low Dam and Hindiya Barrage tell us about state power and primordialism
     - British influenced
     - Both primordialist in standing
     - Aswan Low Dam bad
       - Caused famine
     - Hindiya Barrage Good
       - Cured malaria
     - Why?
       - Hindiya barrage was based off of a real need and considered the inhabitiants.
   - Aswan High Dam and Kut Barrage tell us about how states dealt with urbanization
     - Both american influenced
     - Both tell us about how countries interpret urbanization
     - Both tell us about how countries look to the past???
     - Both nationalist symbols (?)
       - defy foreign influence by construction of self-sufficient projects as the cold war hardens
   - Conclusion
#  Egypt, in particular, repsents two sections. The construction of the Aswan Low Dam is a particular reflection of primordialist perceptions by the British, but also born out of the inherent processeses of de-Ottomanization that occured near the turn of the 19th century. The Aswan High Dam, with its construction coming only three years after the nationalization of the Suez, reflects the power of American influences and follows the trend of legimitizing Nasserism by tying it to state infrastructure.

 # Iraq also respresents two distinct periods. The construction of the Hindiya Barrage by William Willcocks, the same engineering who constructed the Aswan Low Dam, marked the ascendence of the Young Turk policy of public infrastructure of a top-down modernization process. The Kut Barrage, with provided for the later construction of the Shatt al-Gharraf canal, would be the foundations and birth of the Dujayla land reform project, a heavily American influenced projects directed with the help of UN institutions.

#  The Aswan Low Dam and the Hindiya Barrage share more than just their creator, they were constructed with particular primordialist views. In particular, both dams were percieved as a "gift" towards the inhabitans of Egypt and Iraq, and seen to follow a series of "great works" extending back to the Pharonic Era and the Bablonyians. Particularly, the Philae temple would dictate features of the Aswan Low Dam, and Willock's conceptions of "Eden" within Mesopotamia would encourage him to take on the Hindiya project. With both technocratic reasons and religious influences, the construction of Willcock's dams explains the lack of foresight on later problems caused by the Aswan Low Dam.

 #  Both the Aswan High Dam and the Kut Barrage were both constructed under states with relatively young governments, with both governments utilizing the dams for legitimacy. Secondary effects of the construction of both reflected a conceptual "maturation" of the state, with the Aswan High Dam erasing Nubian legacies of the past and delinating a future, and the Kut Barrage's connections to the Dujayla Land Project premised along a distinctive "American self-sufficiency" model.
# . Notably, discussions of ruins and bibical records lie in the descriptions of Hindiya barrage. Naval notebooks describe the ruins of Bablyon and orientalist tropes, such as notions of "Lakhmid frontier tribesmen" and "the sedentary people of the Euphrates" footcite:great_britain_iraq_2014. These ideas with very little basis are extrapolated to chart out the basis of dry canals.

  #  - Talk about how the Hindiya barrage eliminated malaria near it (iraq, committee of officials)?
#     In many ways, the opening of the Kut Barrage is a front runner to Nasser's legitamacy via the Aswan High Dam. DiCapua describes Nasserism as "a question for a kind of dignity that formed the inner meaning of the word /independence/" footcite:di-capua_gatekeepers_2009. Like Aswan High Dam, the Kut barrage took on a life of its own as a nationalist symbol, used to help legitimize a young government and to mold ideas of a future.

    # Originally proposed by William Willcocks during the construction of the Hindiya Barrage, the Kut barrage remains the oldest continunally functioning barrage along a main river in Iraq footcite:abdullah_water_nodate-1. The Shatt al-Gharraf canal, which links the cities of Kut and Nasiriyah, could be used for irrigation purposes if the flows were regulated. This was greatly appealing to the Iraqi government, given that the land tracts alongside the Shatt al-Gharraf canal were quite large footcite:noauthor_kut_1939. Breaking ground in , the Shatt al-Gharraf irrigation project, dubbed the Dujayla project, would have to wait until the Cold War to begin.

    # The opening of the Kut Barrage was the last public event King Ghazi of Iraq attended before his death footcite:noauthor_king_nodate. Combined with President Barham Salih's visit to the Kut Barrage over eighty years later footcite:masum_president_nodate, these mirroring events give a glimpse at how the Kut Barrage has been used as a symbol. With both events occuring a few years after a major political shift (from

#   Discussions about the al-Gharraf canal were described as returning the canal to "the course of the of the main Tigris channel during the Islamic Era more than 1,000 years ago" cite:podsiadlo_tigris_1966. These feelings were common, as Kut Barrage was conceived in the same line of thinking as the Hindiya barrage.  What differentiates the Kut Barrage from the Hindiya Barrage was the fruits of the dams. The Hindiya Barrage succeeded by replacing a dysfunctional, pre-existing dam, while the Kut Barrage attempted to chart a new path by delinating the urban and rural.

# With the rAevival al-Gharraf canal described as "identical to the course of the main Tigris channel during the Islamic Era more than 1,000 years ago" footcite:arab_world_66, the Kut Barrage's existance simultaneously held the notion of the returning into a once-great past. This is unsurprising, as the Kut Barrage was conceived in the same line of thinking as the Hindiya barrage.




* Introduction
  Massive infrastructure projects within the 20th century have typically been harnessed for nationalistic purposes. While most analysis focuses on the nationalism generating certain types of public works projects, projects constructed under colonial governments and then semi-independent governments reflect much upon the status of a state as well. Irrigation projects in particular are interesting as they are the nexus for a multitude of interests. Dams and irrigation projects may be built to tame natural events such as flooding, used to generate electricity to support a growing population, used as irrigation channels to allow for more productive agriculture. Beyond the technocratic goals, irrigation projects are complex, often requiring outside expertise, and are capital intensive, often requiring the explicit support of the state. As a result, not only does the usage of irrigation projects reflect the goals of the state and the engineers, but the secondary effects such as urbanization, land reform, and the process of construction all refract different interests. Notions rural modernization and the usage of dams as nationalist symbols allows for greater understanding of the nationalist psyche. The kaleidoscope of actors in Egypt and Iraq, from the British colonial powers and the Khedive, to the Young Turks, to the newly created "independent" states, all sought to realize their visions of the future via irrigation projects.

  Viewing irrigation projects holistically allows them to be a useful lens in analyzing how states conceived of the past and the future. The Aswan Low Dam in Egypt, alongside the Hindiya Barrage in Iraq, were both constructed by William Willcocks, and influenced by similar biases. Willcocks, in the construction Aswan Low Dam, sought to manage the expectations and desires of the British public to preserve the Temple of Philae, while simultaneously managing his desires to build grand works that succeeded the Pharaonic era. The debates around the minutiae of the Philae Temple, which captured British public imagination, is a reflection on how the British empire saw itself as a safekeeper of particular points in history.

  The Hindiya Barrage, although equated to the Aswan Low Dam in newspapers, was also influenced by Willcock's desires to revive Mesopotamia. The notion that he could revive Eden within ancient lands captured him, so much so that when he retired after the construction of the Hindiya Barrage, he published a book in 1919 entitled /From the Garden of Eden to the Valleys of Jordan/ footcite:ozden_pontifex_2014.

  The differences in outcomes of the Aswan Low Dam and the Hindiya barrage arises out of the level of influence the British engineers held over the dams. The engineers of Aswan Low Dam ignored previous attempts at controlling the flow of the Nile footcite:cook_engineering_2013, and built a dam that needed to be raised multiple times, and was the root of the 1942 food shortage [[footcite:mitchell_rule_2002][pg. 40]]. The Hindiya Barrage, on the other hand, was a replacement for a crumbling rubble dam, which meant that there was no opportunity for the engineers to ignore the past. The success of the Hindiya Barrage, fully functional until it was replaced in 1989, is indicative of the value of learning from previous irrigation attempts.

  If the Aswan Low Dam and the Hindiya Barrage are reflections of how the British empire saw the states of Egypt and Iraq through primordialism, then irrigation projects post-independence were reflections of a state attempting to build a future that distinguished the rural past and the urban future. The Aswan High Dam, and the urbanization boom of the city of Aswan, was enmeshed with Nasserism's desire to valorize the state. Sealing of the past through both metaphorical and physical means, the Aswan High Dam itself was meant as an example in Egypt.

  The Kut Barrage foreshadowed the arrival of American influenced land resettlement projects, such as the failed Dujayla project. While the Dujayla project failed spectacularly, its failures can be traced not only to the influence of American technocrats during the Cold War era, but even further back to the 1933 Law Governing Rights and Duties of Cultivators. This law, which was passed right as the Kut Barrage broke ground in 1934, increased the potential for profits for irrigation pump owners and landholders, incentivizing them to irrigate their lands. As a result, this created a top-down model of irrigation development, which would later lead to the failure of the Dujayla project.

  Ultimately, these four irrigation projects can be separated into two distinct periods. Irrigation projects before the fall of the Ottoman Empire were symbols looking towards the past, reflecting primordialist tendencies. The oversight of British engineers on these projects, combined with the relative free-hand given to them by the British government and the Young Turks, allowed for the construction of irrigation projects whose builders believed they were succeeding an ancient legacy. Irrigation projects following independence, in contrast, were nationalist symbols of the future, sealing away the past while it promised an urban future with a remade rural class.

* The Aswan Low Dam and the Hindiya Barrage
  The building of the Aswan Low Dam and the Hindiya Barrage were both born out of the same primordialist tendencies. Technocratic desires for a more agriculturally productive Egypt provided British engineers a chance to impact Egyptian history, marking the birth and development of the Aswan Low Dam. Specifically, the discussion and framing of the Aswan Low Dam were centered around the dreams of British engineers to succeed the developments of the Pharaonic era. Eventually, as the work of Timothy Mitchell and others have shown, this type of top-down development, with a focus on the past and ancient civilizations rather than the realistic needs of the inhabitants would lead to disastrous results for the Aswan Low Dam. In contrast, the Hindiya Barrage was far more successful, particularly because it managed to shy away from the same type of development.

  Constructed between 1899 and 1902 and designed by Sir William Willcocks, the Aswan Low Dam was intended to manage the seasonal flooding of the Nile. Notably, the desire to increase cotton production in Egypt was a primary driver of the construction footcite:noauthor_power_1913. Foreign import bans of cotton, alongside massive foreign capital and financial investment made the Egyptian cotton economy extremely developed, despite a complete lack of more industrialized forms of farming footcite:hansen_egypt_1975. This lack of industrial productivity, coupled with the large population, formed the impetus for the Aswan Low Dam.

  However, one curiosity seized the feelings of the public: the Temple of Philae. A culturally relevant temple located on a small island within the Nile, the temple of Philae was immediately tied to the Aswan Low Dam. The building of the dam would create a reservoir behind it, threatening to submerge the temple itself. Thus, debates on the height of the Aswan Low Dam were thrust into the public sphere, with discourse eventually reaching to Winston Churchill, who wrote a letter to Willcocks that "expressed the sentiments of the public on the lowering of the [Aswan Low] dam to save the Philae temple from annual immersion" [[footcite:willcocks_assuan_1904][pg. 27]]. Willcocks further points out "the height of the dam and the vexed question of the Philae temple" [[footcite:willcocks_nile_1903][pg. 7]], noting the question of the temple drew multitudes of opinions, from "savants and antiquaries, many who were not savants and antiquaries'' as well as the international commission within Egypt, alongside the Egyptian government itself [[footcite:willcocks_nile_1903][pg. 2]]. The agreed upon solution was to place the dam at a height that would leave the temple partially submerged.

  However, demand for additional water caused the Aswan Low Dam to be raised by 5 meters in 1910-1912, and another 9 meters was added between 1930-1933. Willcocks would later critique the raisings of the dam in 1919 stating that the insufficient water supply invited further problems footcite:cook_engineering_2013.

  In a lecture at the Khedivial geographical dedicated to reviewing the Aswan Low Dam in 1904, Willcocks shows no hesitation in mixing historical references alongside his technical work. He repeatedly cites the importance of his work with irrigation regulators in conjunction with historical references about Joseph's arrival in Egypt [[footcite:willcocks_assuan_1904][pg. 23]]. A sizable chunk of this lecture is dedicated to a recollection of history around Joseph, Egyptian pharaohs, and Theban kings, before returning to abruptly lurching back to statistics about the cultivable area surrounding Lake Morris. Curiously, the lecture itself spends little time dwelling on the /current/ residents of the Aswan Low Dam or of Lake Moeris.

  Why did the British public, all the way up a member of parliament, express concern about an Egyptian temple thousands of miles away, built as part of an irrigation project meant to maximize the output of Egyptian cotton? Why did Willcocks flit between history and statistics within his lecture? A dam born out of a sheer economic desire had its economic impacts dulled by cultural desires, in an era not especially noted for its concerns. At its core, the primordialist conceptions of Egyptian history lay at the root of these questions.

  For Egypt, the temple of Philae is a rallying point for British primordialism, since it is assumed that the Egyptians in the early 1900's are derivatives of the ancient pharaonic civilizations. The lack of references to the Egyptians inhabiting the areas around the Aswan Low Dam are simply fait accompli, and require no consideration. Willcocks himself never denies the necessity of the preservation of the Philae temple, he merely takes offense at the idea that he had not constructed an adequate preservation mechanism vis-a-vis a lower dam height. If the Egyptian past is set in stone as a pharaonic civilization, the role of the British is to birth a future via statistics and development projects. From the British perspective, the Egyptians were not worth mentioning because they had no agency, as they existed merely as a line between the two dots of pharaonic history and British guided techno-politics. This notion had significant buy in from the public as well, demonstrating their concern for a temple thousands of miles away.

  Ignoring the local needs and patterns of the local Egyptians lead to disastrous results. Willcocks foreshadows problems with the insufficient water supply upon reflection 17 years later, but the major problem was the lack of foresight on the Nile flooding patterns. By damming the Nile, only one-fifth of the former plains continued to be naturally fertilized via silt deposits. The other four-fifths required fertilizer, with 80 percent of the Egyptian supply controlled by an international cartel. The 1942 food shortage was directly caused by this realignment to using fertilizer, as fertilizer supplies became constrained when war broke out, inducing large numbers of casualties due to food supplies and a malaria epidemic [[footcite:mitchell_rule_2002][pg. 40]].

  In 1875, Midhat Pasha, the Vali of Baghdad, decided to close the Saklawia Canal on account of its gradual decay to become unnavigable footcite:great_britain_iraq_2014. However, as a result of its closing, approximately 750 cubic meters of water per second flooded into the main Euphrates river, exacerbating the seasonal floods from March to May. Further downstream, where the Euphrates splits into two branches, the Hindiya and Hilla, began to experience sentiment deposit issues. As the eastern-facing Hilla branch lay on higher ground than the western-facing Hindiya branch, extra water diverted from the Saklawia Canal caused additional sentiment deposit at the river juncture, threatening to clog the Hilla branch and rendering it unusable. As this area was fertile ground for date palms footcite:money_hindiya_1917, the Ottoman Government decided to build a rubble dam across the Hindiya branch in order to divert more water flow towards the Hilla branch. However, in 1908, the state of the rubble dam had decayed to the point where the Ottoman government solicited outside advice.

  Flush off of his success in the Aswan Low Dam, William Willcocks was hired in light of the Young Turk large public work programs footcite:money_hindiya_1917. Utilizing the staff he built during his years in Egypt, Willcocks constructed a new Hindiya barrage, creating two artificial lakes for the excess water: lake Habbaniya and Lake Abu Dilis. Willcocks brought alongside the same notions he had of the Aswan Low Dam, with the same keen interest in history. His book, the /Recreation of Chaldea/, paints a picture of grand irrigation works from Nebuchadnezzar to Persian kings footcite:ozden_pontifex_2014. With the Hindiya Barrage imagined as the equivalent of the Aswan Low Dam, Willocks approached the Hindiya Barrage with the same mixture of primordial belief about civilization in Iraq as he had in Egypt.

  Evaluations of the Hindiya barrage paint it in an exceedingly glowing light, similar to the evaluations of the Aswan Low Dam. Royal Naval handbooks claim the Hindiya barrage is the "first great modern work" within Iraq footcite:great_britain_iraq_2014 pg 434, placing it alongside the Kut Barrage and the Diyala weir. Malaria had almost completely been eliminated as a side effect of the additional flowing water footcite:officials_introduction_1946-1, and the barrage saw continual usage until 1989 footcite:bin_huwaidin_chinas_2002.

  Ultimately, the reason why the Hindiya Barrage was far more successful than the Aswan Low Dam in achieving its goals was that Hindiya Barrage was built off of an existing need. Even though both irrigation projects were considered to be equivalent by the British public footcite:ozden_pontifex_2014 and were built from the same primordialist biases, the previous existence of the old rubble dam constructed by the Ottoman government meant that the needs of the local inhabitants were already built into the Hindiya Barrage project. Rather than attempting to fit the desires of the archaeologists, the British public, and a whole host of other desires, the Hindiya Barrage was more focused on simply creating a functional replacement for the rubble dam, making it far more successful in its goals.



* The Aswan High Dam and the Kut Barrage
  The construction of the Tennessee Valley Authority provided a model that was emulated across the world footcite:biswas_development_2001. These dams served dual roles, simultaneously serving as nationalist symbols while also sources for state building via the separation of the urban and the rural. In particular, the development of the Aswan High Dam and the construction boom in the city of Aswan in Egypt fused with Nasserism's idiosyncrasies to help legitimize the state, while the Kut Barrage and the Dujayla Land project helped exacerbate an urban/rural divide.

  Dams within Egypt took on a strict political light following 1956. The nationalization of the Suez Canal, supposedly for the purposes of replacing World Bank loans for the construction of dams footcite:reynolds_city_2017, signaled a shift from rooting development projects in ancient civilizations to rooting them in American technocratic ideals. It was believed that the adoption of American models would transform practices that had formed during the colonial period and set nations upon a more self-sufficient path.

  The Aswan High Dam was one of the first major projects of this new era. First proposed by Gamal Abdul Nasser and born out of Cold War dynamics, the literature surrounding the Aswan High Dam is invariably tainted with political motives. Originally due to be funded by the United States, Nasser's alliance with India in forming the non-aligned movement caused the United States to withdraw funding, prompting the Soviet Union to step in in 1959. This has politicized discussions around the Aswan High Dam, to a point where there are significant communities around anti-dam and pro-dam developments.

    Yoav DiCapua describes Nasserism and its associated projects as having "a constant need for public demonstration of its achievements. It was exhibitionist" [[footcite:di-capua_gatekeepers_2009][pg. 294]]. In line with this, not only was the lake created by the dam named after Nasser, the Aswan High Dam also aimed to achieve a massive set of goals: from "full control of the Nile south of the Aswan", to "generalization of cheap and clean hydroelectric power", along with changing the then-current system of basin irrigation to perennial irrigation allowing for two crops a year footcite:abu-zeid_egypts_1997. The famed singer Abdel Halim Hafez composed a song called "The High Dam '', which was broadcasted across Egypt on state-run channels footcite:reynolds_city_2017. The complete absorption of the Aswan High Dam into popular culture simultaneously legitimized the Egyptian regime, even as the dam was financed and designed by the Soviet Union. The creation of Lake Nasser provides a de facto boundary between Egypt and Sudan, both physically and metaphorically representing a break from the Anglo-Egyptian condominium over Sudan.

    At the same time as the construction of the dam, the city of Aswan grew at a frenetic pace between 1950 and 1960 footcite:reynolds_city_2017. The explosion of new housing settlements to accommodate construction workers led to a massive population boom. State funded roads and tourist centers, and an active page of archeological excavation lead to a steady stream of students and tourists in the summer months. The Nubian Museum and the Aga Khan mausoleum accompanied these developments, and helped to root the city of Aswan and the Aswan High Dam both in the national psyche footcite:reynolds_city_2017.

    The development of the city of Aswan and the Aswan High Dam were departures from the construction of the Aswan Low Dam. While the Aswan Low Dam was thought by the British to spiritually succeed ancient Egypt, the excavations and museums marked the opposite. Construction of museums and placing them for the view of tourists allows for the clean definition of what is considered "the past". The towering structure of the Aswan High Dam, compared to the neatly catalogued historical artifacts within museums, provides for a potent nationalist symbol. Egypt was no longer hoped to relive the glory days of the past, but rather had sealed and left it behind while constructing a new future. Even colonial legacies, such as the Anglo-Egytpian condominium over Sudan, which ended in 1956, were to be neatly delineated by Lake Nasser. Through the active role the state played in the construction of the dam, as well as the "exebehitionist" tendencies of Nasserism, the state was able to tie its popularity to the popularity of the dam.

    Maturation under the Iraqi state fell along similar lines as well. At the start of the Cold War, American style influences, especially molded after the notions of independence and self sufficiency began to take hold, beginning with the Dujayla land project [[footcite:pursley_familiar_2019][pg. 127]]. However, these notions did not come from a strictly Cold War perspective, but rather had their roots in the construction of the Kut Barrage, which started in 1934 and completed in 1939. While specific features of the Dujayla land project would be molded by UN institutions with heavy American influence, ideas about self sufficiency along the Tigris would be seeded with the Kut Barrage.

    Originally proposed by William Willcocks during the construction of the Hindiya Barrage as a counterpart on the Tigris, the Kut Barrage remains the oldest continually functioning barrage along a main river in Iraq footcite:abdullah_water_nodate-1. At the time, the ancient canal of Shatt al-Gharraf, which links the cities of Kut and Nasiriyah, had flooding issues, preventing the vast tracts of land alongside the canal from being used for farming footcite:noauthor_kut_1939. Described as returning the canal to "the course of the main Tigris channel during the Islamic Era more than 1,000 years ago" by a journalist footcite:podsiadlo_tigris_1966, the barrage was completed in 1939, with the intention of supporting larger land reform projects in the future. At the start of the Cold War, the Dujayla land project was one of them.

    While the birth of the Kut Barrage began with William Willcocks, the 1933 Law Governing the Rights and Duties of Cultivators was the cornerstone. Previously, a patchwork of Ottoman-era land laws divided land types into three different classifications, mostly held within the hands of the tribal sheikhs and urban landlords. However, following the 1933 Law, land ownership was extended to irrigation pump owners in the case of default by the land cultivators footcite:kiyotaki_ottoman_2019. In addition, the "law granted pump owners, lazma holders, and leaseholders full rights over decisions relating to production, including the choice of crops, choice of seeds (kinds and hybrids), water supply, harvesting, marketing, as well as the hiring of outside labor" footcite:haj_making_1997. This meant that, once the Kut Barrage was finished and the Shatt al-Gharraf irrigated, the subsequent pump owners, who were mostly wealthy and urban [[footcite:kiyotaki_ottoman_2019][pg. 275]], along the Shatt al-Gharraf would hold significant power over the peasants of the newly irrigated land.

    Ultimately, this type of reform exacerbated the rural/urban divide and helped to drive land resettlement projects. The ambition of these land resettlement programs reflect the socioeconomic state of Iraq, which had experienced significant budget surpluses due to increased oil revenues footcite:adams_pre-revolutionary_1963-1. Top down modernization schemes were devised, such as those used in the Dujayla land project, and were largely driven by foreign and international expertise [[footcite:pursley_familiar_2019-1][pg. 131]]. The notion that the rural peasants desperately needed to be modernized stemmed from land reform laws, which reduced the agency of the rural peasants. This made it such that, when viewed from a foreign perspective, the rural peasants were uneducated and needed teaching, when in fact they were shackled under a series of complex land reform laws. In addition, pump owners and landowners sought to make large capital gains from increases in the value of the land through irrigation schemes [[footcite:kiyotaki_ottoman_2019][pg. 242]]. This combination of a foreign conception that rural peasants were undereducated and unaware of their needs, together with a class that desired higher returns on their land via foriegn investment created the conditions for failure in the Dujayla project.

    These new attempts at remaking the rural class speak to the desires of the Iraqi state, and the gestation for these projects began with the Kut Barrage. The significance of this is born out by the opening of the Kut Barrage, the last public event King Ghazi of Iraq attended before his death. Speaking to how his father held an interest in the barrage footcite:noauthor_king_nodate, this event would occur again over eighty years later, with President Barham Salih's visit footcite:masum_president_nodate. These visits speak to the barrage's symbolic value for the future, with both heads of state visiting only a few years after significant political turmoil.

    The similarities between the Kut Barrage and the Dujayla land project to the Aswan Low Dam and its aftereffects are notable. Both projects were driven in an explicit top-down model that favored ideals over realities on the ground. The failure of the Dujayla project lay in the salinization and outbreak of disease, both of which were determined and understood in the early years by UN technocrats [[footcite:pursley_familiar_2019-1][pg. 127]]. Despite early warnings, the desire for a cohesive family unit that was self sustaining prevented project workers from intervening. As a result, the Dujayla land project collapsed only a few years later. Likewise, issues with raising the Aswan Low Dam were foreseen by Willcocks in 1919 footcite:cook_engineering_2013. In undervaluing the historical experiences, both imperial narratives from the British and technocratic narratives from the US lead UN process would cause both projects to fall apart.

* Conclusion
Irrigation provides a dearth of knowledge, and provides a useful lens for the evaluation of nationalism. The massive capital needs draw upon a diverse set of individuals that reflect many aspects of the ruling state, from the politicians to the engineers. The secondary effects of dams, hand-in-hand with the secondary effects of a massive capital injection, shows us how these ideas are reflected on the ground, and provides a testing ground for the durability of nationalism. The development of the Aswan Low Dam and the Hindiya Barrage, the two "great works" of irrigation that occured at near the turn of the century, shows the devastating effects of primordial and orientalist biases if not tempered by historical experience. The Aswan High Dam and the Kut Barrage provide an insight to how the state used these large infrastructure projects to memorialize the past and shape the future. Irrigation projects are useful case studies in understanding how disparate groups of technocrats, aristocrats, and citizens affect and interpret state driven modernization.




    # The secondary effects of dams are not yet well studied within a social context, mostly due to the fact that environmental impact assessments were not carried out until the Tokyo meeting of 1970 footcite:biswas_development_2001. Addtionally, these effects are almost completely studied within a economic or environmental frame, and not a social or historical one. The development of the Aswan Low Dam and the Hindiya Barrage, the two "great works" of irrigation that occured at the turn of the century, shows us the devastating effects of reshaping local lives without sufficiently understanding the customs of the local inhabitants. The Aswan High Dam and the Kut Barrage shows us how urban development and rural development, when melded with desires of the government to prove legitmacy have exasterbated rural/urban divides and take on symbolic roles of breaking with the past.


    #+begin_export latex
    \printbibliography
    #+end_export
