:PROPERTIES:
:ID:       26E7CAC1-A095-488F-A538-7A39BAA0A4A0
:END:
#+SETUPFILE:./hugo_setup.org
#+HUGO_SLUG: religion_and_modernity
#+title: religion and modernity

[[id:12580BAB-8366-47AD-A690-BAB8B773FA85][fall 2021 classes]]
* Week 2 reading response
  :PROPERTIES:
  :ID:       9A3455F7-8919-463B-AB10-9566B8A53E4A
  :END:
  The competing narratives of secularization this week seem to be akin to blind men reaching for the elephant: each individual feels a different part, and tends project their understanding off of such. Taylor, for example, begins with by introducing the concept of "closed world system", which is a relatively beign rehashing of the concept of a "closed form solution". Taylor tells us that there exists internally consistent models whose abstractions may not map distinctly to the real world, yet these imperfect models are still widely adopted and lived in different ways. Gregory views one of these models as the economic model: that there exists a sufficient level of abstraction such that people can begin to see all things as something to be consumed, which in turn begins as a contagion into other spheres, leading to the secularization we see today. Berger and Casanova offer explanations aligned with the state, Berger talks about the interactions of religious insititutions and their attempts to differentiate one another upon the state managed laizze fair religious market, and Casanova ties religion to the soverignty and the decline of monarchic systems.

  Yet we have still not arrived at the entire elephant. Theories about the "curious fact" of the Westphalian system are well discussed. Arguments about how secular nationalism replaced ethnic and religious identity for a national identity based on civic and secular norms are common, yet they are somehow orthongal to the discussion of modernity. If we limit the concept of modernization to when the state began to exert control (either directly or by creating a free market for religion), the contemporary world then offers a variety of examples on how this process is handled, from India to Uruguay to Malaysia, which would then appear to refute this freefloating idea of "religion" offered up by readings this week. Berger and Taylor assumed that there is a substance to religion that can be traced and compared across time and space in order to measure its shape. As Azba pointed out, there is a discontinuity between how academics theorize religion and how people make use of religion. If we think about the fact that states and people do not arbitrarily use religion, I wonder if the models proffered this week are workable.
* Week 4 Reading Response
  This week, we're presented with Asad's seminal work on demarcating the secular and the religion, alongside the Lowith-Blumenberg debate of whether secularity is merely a transmutation of previous Christian ideas, with the encounter of modernity replacing the power inside the vacuum. Casanova blurs the lines together, repeating the metaphor of the smashing of the monestary walls, noting that both sides have seeped into one another. Duara approaches this idea from the process of identity formation, noting how religion was used a tool to reinforce or advocate for change for specific groups.

  These are all good points worth considering, and we should all consider them carefully. While trying to avoid the stereotype of the grad student that tears everything down, I think we must consider the deep structures available. Duara notes that the lack of definition for what religion *is* allows the state to constantly breach the secular and religious spheres (204). I think the readings this week also largely fail to make proper distinctions for what they consider to be religion, reinterpreting religion to be what is absent after the arrival of secularity, as if religion can be interpretated in the wake of modernity. To me, these ideas are too fluid, and lack both proper morphologic and semantic distinctions. In tracing the geneology, Lowith, Blumenberg, and Asad all fall into the same trap, and end up tracing the genology of religious artifacts and religious people, not religion itself. Casanova has largely given up this view, accepting that the venn diagram of religion and secularity is muddy and should be tested through his three theories.

  So what *is* religion then, if we believe that the Lowith/Blumenberg/Asad geneology is actually a historiography? Duara gives us a hint, through Reisebrodt's idea of 'referential legitimiation' (199): a religion is a religion *because other religions consider it to be a peer*. This is an old Ferdinand de Saussure idea, who theorized that a word is a word not because of the association between the letters/sounds and meaning, but rather because a word stands in contrast to other words. The word 'cat' is useful not because it means the literal animal, but because it is different than the word 'dog', or the word 'snake'. Later linguists have refined this idea to the concepts of "paradigmatic" (relations among units that that occupy the same position in the stream of speech) and "syntagmatic" (relations among units that occur in successive speech). Applying the paradigmatic and syntagmatic concepts back to religion, Duara has already started the paradigmatic approach, looking *across* different religions in East and South Asia, and comparing the various similar structures. However, I think we can move towards the syntagmatic approach with a closer examination of the smaller religions. Duara leaves out how other religions felt about Sam Kauw Hwee, or the Chondogyo, or the Caodai. However, just as smaller, artificial languages allow the linguist to test their hypotheses, I think smaller religions provide a better lens to understand the encounter with modernity, because they are not subject to the same internal gravity that larger religions are bound by.
