:PROPERTIES:
:ID:       A6CFA0B8-6A55-4487-8C98-002DC102147F
:END:
#+SETUPFILE:./hugo_setup.org
#+HUGO_SLUG: sloan_white_corporate_islam
#+TITLE: Sloan-White: Corporate Islam

Tags: [[id:B296A87C-D41F-4992-9F1E-ABF6896B69DB][books]], [[id:BB2783B7-0E6B-4886-8007-EC63A9C67096][islamic jurisprudence]], [[id:9D4C01B9-516D-4DA5-A653-CA71D8931F2A][islamic jurisprudence lecture 3]]

Sloane-White, Patricia. Corporate Islam: Sharia and the Modern Workplace. Cambridge: Cambridge University Press, 2017. https://doi.org/10.1017/9781316875605.

- Distinguishes [[id:60238003-519B-4EC2-BA79-95D114DF0C50][zakat]] between [[id:178CA9E7-B07B-4E9D-91F6-7BB4DEF5CEB8][zakat al-mal]] and [[id:C0B5D535-4ACB-4B58-A538-C0004F670ACE][zakat al-fitrah]]
- what are the possibilities of corruption in zakat based insitutions?
- strange interpretaion of zakat on income taxes?
- using human capital accumulation as the safety valve for capitalism instead of wealth accumluation?
- zakat as an economic motivator - banks can't hold onto large cash reserves since zakat eats away at it
- are there interest rates in [[id:19767910-0590-44C4-850A-672522D7B126][malaysia]]?
- corporations - are they people? are they assets? what about non-public corporations?
- this discussion cannot be separated from [[id:D35F8653-70A4-4D69-97CE-963027822C78][interest rates]]
- zakat as tax writeoffs, what about zakat during the [[id:BEA3898C-4D64-450E-9A9D-BB35B463BB49][1997 asian financial crisis]]?
- paper trail, does the paper trail aspect of htis makes it so that the increased transparency puts up greater barriers?
- most of these new charities work to solidify the status quo, is this a status based thinking of zakat?
- crowding out the local NGO's, creating a sense of who is poor and who is not
