:PROPERTIES:
:ID:       09FA48AE-B268-472C-9EA0-3CAD498B071D
:END:
#+SETUPFILE:./hugo_setup.org
#+HUGO_SLUG: un_and_global_governance_final_paper
#+EXCLUDE_TAGS: noexport
#+LATEX_CLASS: koma-article
#+latex_header: \usepackage[bibstyle=numeric, hyperref=true,backref=true,maxcitenames=3,url=true,backend=biber,natbib=true] {biblatex}
#+latex_header: \usepackage[margin=1in]{geometry}
#+OPTIONS: toc:nil title:nil
#+latex_header: \addbibresource{~/Dropbox/bib/refs.bib}
#+TITLE: UNAMI's Stumble into Sectarian Identities
#+AUTHOR: Peixian Wang
#+DATE: 2021-05-11


#+BEGIN_EXPORT latex
\begin{titlepage}
\begin{center}
{\Large UNAMI's Stumble into Sectarian Identities \par}
\vspace{2cm}
{\large 2021-05-11}
\end{center}
\vfill
Peixian Wang\\
\end{titlepage}

#+END_EXPORT


* Abstract
#+BEGIN_abstract
    The United Nations Assistance Mission in Iraq (UNAMI) has generated numerous reports on their engagements with the Iraqi political system since 2003. At the same time, Iraq has developed into a unwritten sectarian form of government, where particular cabinet posts are reserved for different groups. This paper evaluates, what, if any, role UNAMI has played in preventing the formation of sectarian identities, in reading UNAMI's reports from 2003 to 2010. Borrowing Fanar Hadadd's four layer framework in understanding sectarian identities, I find that UNAMI's engagements with key political events have not addressed the formation of sectarian identities.

#+END_abstract

* Introduction

#+latex_header: \renewcommand{\baselinestretch}{1.5}

Identity formation and notions of belonging are at the very heart of the modern Iraqi state. Following 2003, individual ministries have been given to sectarian groups, in an unwritten system known as the /muhasa ta'ifia/. The Kurds, the Shia, and the Sunnis each assert a different claim upon particular cabinet posts. While most studies have focused upon the effects of the American state upon the Iraqi government, few have conducted a review of the effects of the United Nations Assistance Mission for Iraq (UNAMI). This paper attempts to define the exact effects of UNAMI, between 2003 and 2010, focusing on the reports UNAMI has provided.


What follows is a reading of UNAMI reports to the Secretary General, from 2003 to 2010. Within the reports, UNAMI has responded to major political events in three ways: repeated calls for unity, linking de-escalation of identities with land boundaries, and a checklist style inclusion of minorities. Borrowing a framework for understanding sectarian identities from Fanar Haddad, I discuss each of these three engagements and how they have inadvertently supported the rise of sectarian identities. Adding onto the three ways UNAMI has engaged, I also note that UNAMI has curiously not engaged on the religious or doctrinal level with sectarian identities. I end with discussing how UNAMI's engagements within the reports are almost always with the manifestation of sectarian identities, and as a result fail to halt the entrenchment of the identities themselves.
* Methodology
  This paper is an analysis of UNAMI reports, between 2003 and 2010, found through the UNAMI websites. UNAMI reports are prepared for the UN Secretary General, mandated under multiple UN resolutions: paragraph 30 in resolution 1546 in 2004, paragraph 6 in resolution 1770 in 2007, and finally revised under paragraph 6 of resolution 1883 in 2009. Each report is split into three main sections: a section regarding the key political developments within Iraq, a summary of what UNAMI has accomplished, and observations. This paper will primarily focus on the summary and observations of the UNAMI reports, comparing the discourse to major political events and trends.

  A methodological note must be made. UNAMI reports are not for a private audience, nor are they opinion pieces. UNAMI, by virtue of being a political support mission, must maintain good relations with the Iraqi government. As a result, it is highly likely that UNAMI reports are "sanitized" before release, and possible that analysis on them fails to account for rigorous internal debate. However, in light of the bully pulpit that UNAMI holds, as it holds "enjoys good relations with a wide range of actors from across the political spectrum" citep:united_nations_report_2007-2, it is important to carry out an analysis of how UNAMI has responded to events within its political reports, and what UNAMI fails to report on.

The time frame of 2003 to 2010 is chosen for two major reasons: it is bookended by the US invasion of Iraq and the 2003 constitutional drafting process, and the re-election of Prime Minister Nouri al-Maliki, which provides a useful case study on a government that appears pluralistic but in fact entrenches sectarian identities. In addition, ending with 2010 allows for a study of sectarianism that is not overshadowed by the formation of the Islamic State. While the Islamic State is a form of sect-based violence, it remains outside the scope of a study on the effects and developments of sectarian identities, as it remains a violent outlier expression of sectarian identities. Most sect-based violence is on a far lesser scale, and more pervasive to society. In addition, limiting the analysis to before 2011 allows the study to remain unaffected by the Arab Spring, another potentially confounding factor in the discourse.
* Background

 Scholarship on contemporary Iraq has been fixated on "sectarianism", and yet there are little clear definitions of what "sectarianism" is. One particular discourse is the Sunni/Shia schism, drawing a historical line between the schism of Islam and contemporary actors today. This primordialist approach holds that identities are static and unchanging, and that recent violence and sectarianism are nothing more than expressions of old hatreds. The opposition to this view is the instrumentalists, who perceive sectarianism as being influenced by elites, who maneuver symbols and discourses of sect for their own goals. Yet, as Fanar Haddad points out, these two views are both flawed, the primordialists fetishize religious doctrine while the elite-based discourse the instrumentalists claim ignore the fact that elites are the products of their own societies [[citep:haddad_understanding_2020][pg. 43]].

 Yet the debates between these two sides, and the ability to move beyond these views need not detain us. Rather than reading sectarianism as mutually exclusive viewpoints between doctrine and politics, other scholars have provided different frameworks for the analysis of sectarianism. Hinnebusch provides a viewpoint of sectarianism through a three-tier model, stating that identity formation in a sect based manner happens at a supra-state, state, and sub-state level citep:hinnebusch_identity_2020. Haddad extends and transposes this model, rather than seeing it as an onion in which each identity encircles another, Haddad first adds a doctrinal level and suggests that each level is another way to view the sectarian identity box, that doctrine, sub-state, state, and supra-state are four sides to sectarian identity that must all be analyzed in tandem. Just as a polygon only becomes a rectangle when all four sides are drawn and closed, sectarian identity can only be understood when all four are observed at once.

Haddad's framework is used to analyze the events of the January 2005, December 2005, and March 2010 elections on the sub-state and state level. In addition, the question of Kirkuk and Article 140 of the 2003 Constitution of Iraq will be analyzed using the state and supra-state level. UNAMI's engagements with minority inclusion within government formation is also analyzed on the state level. The goal is to provide different snapshots of political flashpoints in which UNAMI could have intervened, and in particular flashpoints that were integral to the solidification of the sect-based Iraqi political system.


* Repeated Calls for Unity
  The UNANMI reports, in almost every report starting 2005, has made a point to call for national reconciliation and settlement of disputed territories. For example, a report from November 11th, 2009 highlights the "three successful elections and a national referendum, generally considered credible and broadly participatory" citep:united_nations_report_2009-3. In another dated July 29th, 2010, the UNAMI report describes the successful electoral process on June 2nd, and warns that a prolonged government formation process would lead to a loss of credibility for the ruling government citep:united_nations_report_2010-1. The January 2005 provincial elections and the December 2005 parliamentary are important steps in the formation of Sunni sectarian identity, and the December 2010 elections helped to entrench sectarian identities on all sides.

  Bland statements that treat peaceful elections as successes flatten history and view it as a singular step function that, once achieved, has no further ramifications. Counting the number of successful elections, or elections without significant violence fails to account for the differences in voter patterns. The 2005 elections were marked with the formation of the United Iraqi Alliance, consisting of mostly conservative Shia parties citep:adam_carr_republic_2005, whereas overtly sectarian messaging began to abate by 2009, only to return in 2010 as Prime Minister Nouri al-Maliki campaigned on a Shia identity [[citep:rayburn_iraq_2014][pg. 42-44]].

  Sunni groups originally boycotted the January 2005 provincial elections, under the assumption that Sunni populations were a majority of Iraq [[citep:haddad_sectarianism_2011][pg. 154]]. As a result the local governments in the provinces of Ninewa, Salahadin, and Diyala became controlled by minority Kurdish and Shia parties[[citep:rayburn_iraq_2014][pg. 126]]. However, the UNAMI report blandly states "a large number of Iraqis in many parts of the country exercised their right to vote or ran as candidates'', stating only that "turnout in areas with a majority of Arab Sunnis was markedly lower than for other communities" citep:united_nations_report_2005. Notably, the terms "sectarian" or "sectarianism" does not appear until the September 2005 report, which it only mentions in passing as "rising sectarian tensions" citep:united_nations_report_2005-2, an ominous foreshadowing for the outbreak of civil war a year later.

  UNAMI's 2005 analyses fail to grasp the political space these nascent sectarian identities were competing within. The outbreak of sectarian violence a year later, after a supposedly successful election, is not a rise in "sectarian tensions". Rather, Sunnis had attempted to compete on the sub-state level by boycotting the elections, in an attempt to completely overturn the US-developed framework. When they realized their blunder, they pivoted to compete on the state level by participating in the elections. When the December 2005 national level elections failed to yield a Sunni majority, sectarian tensions boiled over within Sunni provinces. While the UNAMI reports portray the Sunnis as switching sides from non-participation to participation and an unrelated outbreak of violence a year later, the Sunnis had simply pivoted tactics. In other words, Sunnis had never switched sides, they had remained on their own side the entire time, and were simply switching tactics.

 # The UNAMI report on December 7, 2005 mentions sectarian identities, but only within the context of violence and security. This reflects a greater trend in the UNAMI reports, where sectarian identities are only mentioned as a security issue, specifically relating to sect-based violence. However, Iraqi analyst Nibras Kazimi has called the December 15 elections a "census", wherein most Iraqis voted for their most closely aligned sect <INSERT NIBRAS CITATION>. This shows the contradiction in understanding sectarianism purely through the security lens. The first UNAMI report after the December 15th elections, dated March 3, 2006, stated that multiple Sunni tribal leaders, and proceeded to call for unity and reconciliation, in light of the bombings of the al-Askari mosque in Samarra citep:united_nations_report_2006.

#  To borrow Haddad's model, all four sides of sectarian identity are present in 2005, and yet the 2005-2006 UNAMI reports fail to address sectarian identities beyond securitizing them. On the sub-state level, sectarian identities can be found in the provincial elections, on the state-level, the participation of Sunnis is treated as a checklist, a problem that has been solved once a single successful election has occurred.

 # <Talk about how on the substate level X exists, talk about how the national level is addressed as part of a checklist inclusion>. The danger in addressing sectarianism as purely a security issue is one of treating the symptoms and not the root cause. Sectarian violence arises as a downstream effect of sectarian identities, meaning that calls for unity and reconciliation while bouts of violence occur will inevitably fall of deaf ears. This approach is similar to most mainstream narratives of most civil wars, where violence is located in terms of macro-level ideologies citep:kalyvas_logic_2006. When treating sectarian violence as one large item to be solved, it creates an all-or-nothing situation, where it accords the state's monopoly on violence and rule of law as the primary solution, and mediation of grievances on a national scale as the path to peace. Sectarian violence, which is a manifestation of sectarian relations, is criminalized and the best solution is described as a "grand compromise" citep:united_nations_report_2008-2. These "grand compromises" are fundamentally unworkable, as they simultaneously privilege the power of elites to control manifestations of sectarian violence, while ignoring the doctrinal, substate, and supra-state levels.

Furthermore, The UNAMI approach of addressing grievances through the mechanisms of the state leads UNAMI to be blind to the sectarian actions that different arms of the government carry out. During the run up to March 2010 elections, the de-Baaification committee, which had begun as a way to root out candidates with Baathist dies excluded more than 500 candidates from running for political office [[citep:rayburn_iraq_2014][pg. 210]], yet this event remarkably fails to show up in any of the UNAMI reports. The reports hold several mentions of the debates that occurred during the original draft De-Baathification laws in 2007 citep:united_nations_report_2007, citep:united_nations_report_2007-1, but it seems that once the committee had been impaneled, UNAMI failed to report on its activities, even when the committee barred candidates on spurious grounds. Practically anyone who held a civil service role during the Saddam Hussein era had some Baathist ties, and the committee exploited this in favor of Shia sectarians, banning Sunnis weeks before the election and throwing the electoral lists into chaos [[citep:rayburn_iraq_2014][pg. 210]].

In March 2010, the parliamentary elections yielded a poor result for then-incumbent Prime Minister Nouri al-Maliki. al-Maliki's State of Law coalition proceeded to win 89 votes, while the predominantly Shia National Iraqi Alliance won 70 votes. The surprise was the Iraqi National Movement (/Iraqiya/), a coalition of parties from Sunni provinces with significant support in the Shia south, which had won 91 votes citep:adam_carr_republic_2010. A plain reading of the Iraqi constitution would mean /Iraqiya's/ 91-vote plurality in the 325 seat parliament gave /Iraqiya/ the first mandate to form a government. In a bid to stay in power, Prime Minister Nouri al-Maliki urged Supreme Judge Medhat al-Mahmood for a ruling on the constitutional requirement that the largest party following the elections first receive a mandate to form the government. al-Maliki asked whether the law meant the largest party after vote tallying, or the largest party to cobble together a coalition within government. Judge Medhat helpfully ruled the latter, effectively invalidating the election, ruling that any party which could cobble together a coalition of votes, or 163 parliamentarians, would receive the first mandate [[citep:rayburn_iraq_2014][pg. 212]]. al-Maliki proceeded to cobble together a government of national unity, on the surface composing of a cross-sectarian group, but instead bound together by the arrangement that parliament would not hold individual ministers accountable for their actions [[citep:al-ali_struggle_2014][pg. 205]].

The UNAMI reports have zero mention of the ruling and its effects on the Iraqi parliamentary system, rather it mentions the "collective process and reaching agreements that appear to have ended the deadlock in the government formation process" and welcoming the nomination of al-Maliki as the Prime Minister designate citep:united_nations_report_2010-2. Welcoming al-Maliki's nomination has a very real cost of legitimacy, as it ignores the clearly sectarian de-Baathification committee's actions, the rulings of Judge Medhat, and the further entrenchment of sectarian powers. This provides a conceptual parallel to UN stabilization missions and peacebuilding, where stabilization missions often come at the cost of defining which groups are included and excluded in political dialogues citep:curran_stabilization_2020, which may appear to stabilize volatile situations in the short term at the expense of long-term goals. UNAMI, in supporting a government which was effectively unaccountable, provided political space for further sectarian divisions on the national level, similar to how UN missions in the Congo have problems in appearing complicit in human rights violations by the Congolese government.

* Linkage of De-escalation of Identities with Land Boundaries

  Alongside the Sunni and Shia identities, the Kurdish identities is a unique one that straddles international boundaries. During the 2003 American invasion, the Kurdish militias seized Kirkuk, an oil rich city with great cultural importance to Iraqi Kurds, and established it as a "green line" [[citep:rayburn_iraq_2014][pg. 141]]. The question of whether Kirkuk belonged to the autonomous Kurdish region of Iraqi was written into the Iraqi constitution as Article 140, which sets out a process for determining the disputed territory, first through a committee formation process, and then followed by a census and While the constitution stipulated that the process was to be carried out by 2007, Article 140 was never implemented, and briefly threatened to start a scheduled civil war.

  UNAMI was greatly involved in the Article 140 process, hosting multiple mediations and consultative sessions, including clarification of the electoral system citep:united_nations_report_2006-3, citep:united_nations_report_2007, citep:united_nations_report_2008-2. The June 5th 2007 UNAMI report specifically mentions the close working relationship between the Special Representative, UNAMI, the Government of Iraq, and other international organizations citep:united_nations_report_2007-1. UNAMI highlighted its direct involvement within the referendum negotiations, stating the "intra-fractional violence" within Kirkuk and Mosul citep:united_nations_report_2007-2.

  However, the ultimate failure to implement Article 140 reflects on the success of UNAMI. UNAMI urged that the rising tensions following the failure to implement should be solved with national and local leaders working towards resolving the underlying disputed boundaries citep:united_nations_report_2009-1. However, tying the disputes to and sectarian identities to land boundaries fails to respect the sectarian identities at play, by treating the disputed boundaries as the source of the issues, rather than downstream to them. In the case of Kirkuk, even as the national level issues became deadlocked between Arab and Kurdish parties in parliament, local level politics became deadlocked for a different reason. Turkomen and Arab parties in the local council protested the 2006 decision to allow displaced Kurds to vote in the city council elections, and a rushed decision to conduct a census of Kirkuk within five months caused the collapse of the Article 140 committee [[citep:rayburn_iraq_2014][pg. 146]]. As the Article 140 deadline loomed, Shia and Sunni parties joined in to block the Kurdish bills in parliament, and the resumption of hostilities between Turkey and the PKK made the Kurdish maximalist position untenable, setting the stage for a mutual de-escalation of hostilities.

UNAMI engaged with the collapse of the Article 140 committee in two ways: by calling for national level reconciliation by settling land boundaries, and by engaging with local level politics in assuring the inclusion of minorities citep:united_nations_report_2008. While these measures were certainly welcome, they remained on the periphery and ignored why tensions had de-escalated. Kurdish supra-state sectarian identities had simultaneously manifested with the Sunni/Shia state-level sectarian identities had set the stage with the Kurdish offensive against Turkey. As the Kurdish Workers' Party (PKK) restarted its offensive against Turkey, and Turkish airstrikes within Iraq in response caused a political crisis [[citep:rayburn_iraq_2014][pg. 146]], citep:united_nations_report_2008 De-escalation had to occur outside the bounds of the Article 140 process, yet UNAMI continually pushed for reform and inclusion within the bounds.

The Article 140 case provides for a useful case study. On the surface, Article 140 addresses what is fundamentally a land dispute, which is the level that UNAMI engaged upon. The collapse of the Article 140 process and the tamping down of tensions with UNAMI's help appears to have been successful. When a sectarian framework is applied, however, a different picture emerges. When Sunnis and Shias crossed sectarian lines in order to vote against Kurdish parties in parliament, they asserted a state-level sectarian identity, that is, one that accepts the existence of the state of Iraq. Rather than asserting their own identities, the joint vote implies that Sunnis and Shias both did not believe in the reduction of the Iraqi state. In fact, a popular Shia poem laments that the Iraqi flag is not flown in the Kurdish lands [[citep:haddad_sectarianism_2011][pg. 140]], a clear statement that sectarian identities are not mutually exclusive with state level identities. When viewed from this angle, Article 140 becomes a referendum on an Iraqi identity vs a Kurdish one, and this was not a conceptual level UNAMI engaged upon.

In the opposite direction, the collapse of the process and its subsequent de-escalation of tensions was not due to UNAMI either. UNAMI continued to approach the problem as a land dispute, but the determining factor in the peace was the Kurdish over-extension of resources. In asserting a supra-state sectarian identity, the Kurdish maximalists were forced to come to the bargaining table with the Sunni and Shias.


* Checklist Inclusion
Outside of the Article 140 process, UNAMI's repeated engagements with minorities remained largely limited to ensuring minority representation among elections citep:united_nations_report_2008-2, such as helping to establish the Committee on Ethic and Religious Communities within Ninewa citep:united_nations_report_2010-1. The November 6th 2008 UNAMI report calls for "Iraq’s diverse communities and their political leaders to continue to work with one another in a spirit of dialogue and grand compromise in a manner that reinforces the overall national interest" citep:united_nations_report_2008-2.

This type of engagement leads to a form of "checklist inclusion", wherein once certain parties are included within the political process, the substance of how these parties are included are ignored. In particular, power-sharing agreements can manifest as the continuation of conflict dynamics in the Lebanese case citep:delatolla_lebanese_2019, and can be seen in Iraq as well. No sectarian party within Iraq denies the existence of other groups, but all contest the grounds and power structures that arise from a pluralistic state. The incessant conspiracies about fake Shia demographics are a representation of this. Sunnis groups, when they boycotted the January 2005 elections, falsely assumed that Sunnis were a demographic majority citep:rayburn_iraq_2014. As recent as 2009, a Sunni political stated that the notion of a Sunni minority was a "media lie" [[citep:haddad_sectarianism_2011][pg. 155]].

This is where UNAMI falls short. Calls for national reconciliation and "grand compromises" will inevitably fail, because the sectarian groups do not even speak on the same conceptual level. UNAMI calls for a secular, pluralistic Iraq in which all parties are united at the state level, while the sectarian groups see the state as yet another battleground. As long as this conceptual gap exists, the calls for grand compromises will only lead to sectarian dynamics entrenched on the state level, as groups seek to assert their identities, and in so doing, "deliberately discarded the institutions of the state, awarding different ministries to different political parties" citep:dodge_beyond_2020.

To return to the March 2010 elections, the Erbil Agreement, which outlined the power sharing agreements for al-Maliki's government, was never released to the public. While the agreement itself formed a government of national unity, checking off all the requirements for a pluralistic government on the surface, the agreement effectively provided for zero oversight of the al-Maliki government. The Erbil Agreement shows that pluralistic governments can further entrench sectarian identities and dismember the rule of law.

* The Missing Doctrine
While some sectarian analysis overprivelage the doctrinal aspect, attempting to draw linkages between sect and ancient schisms in religion, the UNAMI reports seem to lurch in the other direction and pretend the doctrinal aspect does not exist at all. The UNAMI reports do not bring up the United Iraqi Alliance at all, also ignoring that Grand Ayatollah Sistani's blessing was one of the key reasons for the alliance's formation. The bombing of the al-Askari Shrine, an event which most scholars recognize as a key turning point in the formation of Iraqi sectarian identities [[citep:haddad_understanding_2020][pg. 72]], is recognized purely as an event that caused internal displacement peoples, without noting the religious markers around it citep:united_nations_report_2007,


Sectarian identities are often driven by a combination of religion and politics, with religion and politics existing in a feedback loop with one another, religious symbols can provide for legitimacy for political rulers, but religious minorities require the mechanisms of state for protection [[citep:haddad_understanding_2020][pg. 59]]. However, this model only applies for governments with a functional oversight process. In the case of Iraq, the structural weaknesses of the state and the overtly Shia-leaning state nationalism helped to inflame sectarian tensions. The contestation over demographics is a proxy for the battle over the "cultural ownership" of Iraq [[citep:haddad_sectarianism_2011][pg. 154]]. Images of mass graves are abundant Iraqi discourse, but in the south, mass graves are near-synonymous with the events of 1991 [[citep:haddad_sectarianism_2011][pg. 135]]. Here, it is the mixing of a religious identity and trauma over past political events that creates for a particularly volatile cocktail that inflames sectarian tensions. As Kalvyas describes, "it is the convergence between local motives and supralocal imperatives that endows civil war with its intimate character and leads to joint violence that straddles the divide between the political and the private, the collective and the individual" [[citep:kalyvas_logic_2006][pg. 387]].

UNAMI's reports, in ignoring the religious overtones of the 2005 elections and purely approaching the bombing from a humanitarian perspective ignores the "normative ordering power" of religion, which Brubaker describes as a understanding of what is right and what is wrong, beyond the level of individual behavior citep:brubaker_religious_2015. Ignoring the doctrinal aspect fails to understand the greater issues of society as a whole. When UNAMI fails to report the doctrinal and religious overtones, a key component is missing in the analysis of violence within civil war.

* Conclusion

The UNAMI reports from 2003 to 2010 note the rise of sectarian identities within Iraq, trending towards the entrenchment of the /muhasa ta'ifia/. UNAMI's engagement with the violent manifestations of these identities were on multiple axes: calling for unity and reconciliation, linking reconciliation to the peaceful settlement of land boundaries, and ensuring the representation of minority communities within electoral systems. On the surface, these seem largely successful, successful elections have been held, the constitutional time bomb of Article 140 did not trigger another bout of civil war, and minority communities had access to parliamentary systems.

However, the failures of UNAMI are laid bare when applying a deeper model of sectarian identities. When sectarian identities are understood as having the four consitutant sides of substate, state, supra-state, and doctrinal levels, the UNAMI portrait becomes less rosy. The calls for unity and reconciliation began to look like securitization, demonizing and shutting out non-sectarian parties from parliamentary representation, as the government became more and more sectarian. Defusing the time bomb of Article 140 was not due to UNAMI, but rather a confluence of circumstances. Checklist style engagement on the national level, without being aware of how parties engage with each other leads to further entrenchment of identities.

    #+begin_export latex
    \printbibliography
    #+end_export

* Outline                                                         :noexport:
Tags: [[id:6377293C-2556-4797-9A2B-FED088E549BA][UN and Global Governance]]
** Introduction
** Background
** Sectarian markers and the analysis frame
** UNAMI
   - constitution
   - 2004-2005 elections
   - bombings of the al-Askari shrine
     - strangely does not even show up in the "political developments"
   - 2009 parlimentary elections
     - rulings by the Judge Medhat al-Mahmoud in favor of maliki
       - lack of statement?
     - Vice president Tariq al-Hashimi
       - lack of statement

** Kirkuk
** Christian minorities
** Amman statement of 2005
*** Other related statements
** Independent Electoral Comission
   - Has helped draft electoral laws
** UNDG Iraq Trust Fund?
** 2004-2013 time range
*** pre-[[id:D565EE03-B588-489C-BDB7-DACD67FA5F8A][islamic state (is/isis/isil)]]

# - Key question: has policies of UNAMI failed to curb the developments of sect-based identities?
# - people are fixated on sectarianism (primordialist and others)
# - similar to east timor
  #  - 2005 elections had significant issues
  #   - boycott of the sunnis
  # - 2010 elections had dramatically lower turnout
  # - focusing on specific security *during* the election
  # - fails to consider the rulings of judge mehmat
  #   - March 26, 2010 -> Judge Medhat al-Mahmood has a constitutional interpretation that the first party to form a government was the largest group that could be cobbled together.
  #     - this furthers the sectarianization of govenrment because rather than promoting a rule of law equal to all, it promotes favoring of a specific sect
  #     - maliki's embrace of shia sectarian identity to win the election and pressure of the iranians (international level), meant that this election inadvertantly started the process of rebuilding sectarian identity


# * Focus of sectarian cleansing in kirkuk but not baghdad? from 2005-2006 general security issues
# * Bombing of the al-Askari Shrine in Samarra
# ** Sub-state
# ** State
# ** Supra-State
# ** Doctrinal
# * Rulings from Judge Medhat for Nouri al-Maliki
# ** Sub-state
# ** State
# ** Supra-State
# ** Doctrinal
#   - further empowering of the shia majority
# * Outing of Vice President Tariq al-Hashimi
# ** Sub-state
# ** State
# ** Supra-State
# ** Doctrinal
#   - empowering of the shia majority
# * The status of Kirkuk
# ** Sub-state
# ** State
# ** Supra-State
# ** Doctrinal
# * What Avenues are Available?
# * Conclusion

# 1) Acknolwdge the limitations of the study, that
# ** UNAMI
#  - talk about how the UN has been accused of liddism
#  - talk about how the UN RC system has failed to acctually push for real change
#  - talk about the state of UNAMI

#  - What is sectarianism? What is sectarian identity? Why should we examine sectarian identity this way?
#  - Talk about why the rise of the Islamic State is exceptional, and how sectarianism is not exceptional
#  - Talk about how UNDG Iraq was established in 2004 as one of two trust funds, which was lead by the World Bank and the UNited nations, in joint partnership  with the World Bank. It poured over 238 million USD to funding the electoral governance, which was the plurality (238,201,267/1,359,743,957)
#  - two major governments: the rise of the 2004-2005 Ayatollah Sistani campaign of United Iraqi Alliance and 2010 Iraqiya's vote
#  - jan 2005 elections?
