:PROPERTIES:
:ID:       CABB31F9-5A03-43CE-9E66-204123E3BEAE
:END:
#+SETUPFILE:./hugo_setup.org
#+HUGO_SLUG: wilderness_alpine_personal_statement
#+TITLE: wilderness alpine personal statement

Tags: [[id:DEA6716B-1D34-41C0-9230-640537AC2B68][grad school fellowships]], [[id:BF94E285-63E1-47AC-B228-2359842F79C7][drafts]]

- https://alpinefellowship.com/welcome

__Question__: Does the wild stand in opposition to civilisation, or are they both manifestations of the natural? Is our conception of the wild anthropic, indeed is it sentimental? When is it right to ‘live according to nature’, and when should we turn to science to rewire nature or ourselves?  Indeed, what is our ‘natural’ state? And following a year in which so much interaction has been online, we ask how it affects this theme?

* Draft

The development of French archival science, born in the wake of the French Revolution, was the first conceptualization on the public status of documents cite:di-capua_gatekeepers_2009. This new line of thought, that documents contribute to a nation's heritage, and that access to that heritage should be publicly aligned with the Revolution's rebuttal of the ruling class. The 'holy' King and divine rule were no longer sufficient, and the French Revolution began a process that "brought Christianity down from Heaven to Earth" cite:requejo_coll_1_2015, from the King to the people.

Notions of divinity, and associated priesthood of elites have always played into our conceptions of wilderness. Either as self-declared guardians against barbarians at the gate, or as fonts of reason and order, civilization has always been associated with divinity, and the wilderness with the inverse. Heaven and Hell, order and chaos, civilization and wilderness, all these conceptions stem from one core issue: a lack of understanding of the world's processes.

The earliest notions of the priesthood class interpreted the chaos of the world, divining truth from random actions. This class performed rituals that attempted to control or influence the chaos around them, beseeching rain for crops and recovery from illness. Divining intentions from perceived omens in nature or in dreams, this early class acted as the interpreters of divine will.

In other words, priesthood is an act of information transformation. Mathematicians have a word for actions that change information without losing any details, this is a property called /isomorphism/. For example, a mirror is isomorphic, it preserves all the aspects of light, except it flips them. To be more precise: isomorphism is when two complex structures each have corresponding parts in the other structure, the mirror version of yourself has all your body parts, just like the real you. But mathematicians care about isomorphism not because of their simple physical properties, isomorphisms is imply meaning. The isomorphism of the real you and the mirror you shows that you exist, that your existence in the physical world is real. Is it any wonder that the fantasies of walking through a mirror to another world abound in our cultures?

Back to the priesthood class. The priesthood class acted as human isomorphisms, attempting to take all the information available and translate them into insights. Their isomorphism was not a mirror, but rather a translation, they heard the language of the divine and spoke in the language of humans.

Despite the fall of religion from its apogee from the French Revolution, it did not change the need for people to interpret the world. Instead, as identified by scholars such as Bernard Anderson, the nascent forms of nationalism developed via French archival science grew due to the burgeoning press. The printing press revolutionized how people saw each other and how they saw their communities, entire nations made legible to its citizens through the newspaper.

The awesome power of this has led the field of journalism to great heights, and with it came ideas that the press had the capability to inform and control public opinion, leading to the term of the "fourth estate". Journalism provided an uniform truth, a single way to understand the world, becoming a new papacy in its zenith. Journalists could dictate truth from far away places like Baghdad to people in their homes.

The ability of journalism to provide consensus has been its contemporary downfall. Platform companies and social media such as Twitter and Facebook shatter the conceptions of a consensus, rather they all put forth their own truth. Yet we must also shy away from the tired criticisms of social media and look deeper. Social media, when viewed from the perspective of the user and participant, is an isomorphism in disguise, and with it comes meaning. Instagram and Twitter are mirrors, albeit distorted ones, but mirrors nevertheless. They are the evil versions of ourselves standing on the other side of the mirror.

We must also not lose sight that the platform companies who build social media are not passive actors. They are systems, built and maintained by real people, who consciously and unconsciously impart their biases onto their creations. All technology is a lever, meant to amplify effort and labor cite:alice_maz_priesthood_2017, and these companies are no different. They amplify our voices, our small efforts into massive ones, allowing us unprecedented reach, all the while chipping away at the consensus we have built, bringing more and more chaos into our conversations. In many ways, programmers have replaced the journalists as the papacy at the altar of interpretation, with one key difference: early priests and journalists made the world legible, they were isomorphisms that made things smaller, whereas programmers are the opposite, programmers provide tools to make the world illegible. Priests and journalists reduced the chaos to the average person, programmers cram all the chaos of the world into a six inch screen. If the French revolution brought Christanity to Earth, the social media revolution raises our voices to the Heavens.

Chaos takes the front stage here, because civilization has always been defined its opposition to chaos. Chaos is associated with the concept of the wilderness. Edward Said defined orientalism as a stage, a theatrical stage for which the European West could impart its biases, but a stage that defines the West. The backdrop of the savage Orientals allowed Europeans to feel superior in civilization. This theatre allowed the West to pose itself as a bastion of civilization against the wilderness of the Orient, a repulsive line of thought still seen today. Said also stated that the West could not exist without the Orient, for without a caricature to mock, the West would be forced to reflect inwardly.

Social media now takes the stage formerly occupied by the Orient. All of us are encouraged, through the tools created by the priests of the machine, to act as caricatures of ourselves, becoming the most debased form of ourselves. In a year largely spent on the computer, dreaming of escaping to the physical wilderness of the mountains, I have realized my understanding of "wilderness" only overlaps with "the outdoors'' by happenstance. I now realize wilderness is wherever chaos resides, for wilderness is defined as the inverse of civilization, and chaos is the lead actor. Our wilderness is no longer the outdoors, nearly every inch of this Earth has been explored. Our new wilderness is one of ourselves, and of other people. If divinity and Heaven are ruled by decree, then what does the chaos of humans make?

I am an astrophysicist by undergraduate training, an artificial intelligence programmer by trade, and a Near Eastern studies graduate student. I believe the Alpine Fellowship would provide an excellent opportunity for me synthesize all of my training and education through supporting my research and studies. My current work focuses on the properties of Mandarin and English, and finding the isomorphisms that exist in between. I hope to add Arabic onto that work, as Arabic proficiency is a requirement for graduate degree. I hope that the combination of Arabic, English, and Mandarin yields more insight into languages, for systems of threes are very peculiar in nature. Graph theory teaches us that a triad reveals previously hidden information about the dyadic structures, history teaches us that triumvirates are unstable political systems, and astrophysics is still plagued by the three-body problem. In other words, systems of threes seem to be naturally unstable, and therefore naturally chaotic and wild.

I believe mathematics offers the key to building sustainable policies of statebuilding, not so much the results, but the process for which mathematics is done. I hope to contribute much to the fields of linguistics and reintegration policy, guided in part by the thinkers at the Alpine Consortium.

My research focuses on best practices to reintegrate ex-combatants of militias back into the Iraqi state. While this may seem to be an offshoot, I believe there are significant opportunities to bridge my research and my work. Reintegration and disarmament programs often fail because they are imposed top down, from organizations such as the state or the UN. Critically, these programs fail because these programs do not appreciate the local level politics, often due to issues with communication. My focus on the Iraqi dialect of Arabic aims to help bridge this local-state gap, and my studies on history, sociology, and political science at NYU will help to flesh out these policies. Funding from the Alpine Fellowship would allow me to engage in further research, such as conducting interviews and traveling to volunteer with NGOs.
* Outline wilderness
- intellectual wilderness with [[id:A75E8675-6FA2-427F-AC64-64D3F4DEE1F1][philosophy of science]]?
- [[id:DCE0D2E2-AADF-48D5-B6A6-3952E2530A90][philosphy of programming]]?
- [[id:BC69BD6D-62DE-4309-A194-59223FC65039][continental philosphy]]?
- the new dark age?
- "mathematics is the key to reliable programming -- not so much on the mathematical results, but on the processes by which mathematics is done" - [[id:D43D63F1-C8FA-4230-A6E1-1331E97E4778][Braben - Scientific Freedom: The Elixir of Civilization]]
- godel's incompleteness theorem -> shows that truth is weaker than formal systems
- same with transitions from statistical AI to inference AI
- same with warfare and [[id:E900796C-250A-474B-9054-C0C109C94A24][ddr]] -> io's attempt to build formal systems, but the bespoke systems are always what's needed
  - the formal system of IO's breaks down against the truth on the ground
- novel's about the hashd
- logic and violence in civil war
- chomsky lingusitics and computer science
- collective problem solving from ants -> applicable to computer science
  - might this be applicable to humans as well?
- intracatbility of "wild" problems -> navier stokes and fluids ->
- internet communities?
- we treat the borders of the wilderness and "technology" as two polarities, either extremely well stirred or harsh division
  - academics we must reject these false binaries and realize that nature does not ever engage in well-stirred interactions
  - rejection of the equailbirium and understandings where nonlinearities play a crucial role, fluids/kelvin helmholtz shearing
  - nature as the medium, wilderness as a false target
- warfare in "wild" places?
- context collapse and content collapse
- political instability and Kondratiev wave
- question: Does the wild stand in opposition to civilisation, or are they both manifestations of the natural? Is our conception of the wild anthropic, indeed is it sentimental? When is it right to ‘live according to nature’, and when should we turn to science to rewire nature or ourselves?  Indeed, what is our ‘natural’ state? And following a year in which so much interaction has been online, we ask how it affects this theme?
- iit -> integrated information theory
- madness, psychosis, islam
- epileptic seizures and quantum conciousness
- priests of the machine
- more warfare than ever, on a substate level
- answer: science and technology are not monoliths, thinking about wilderness in this manner is wrong. they are not formal systems, we are barreling towards a new dark age where our systems become less and less reiable, and we assume the isomorphisms of the past hold. the conceptions of "wildness" and "wildness" relies on technology and science always /functioning/, and it's on borders where it doesn't funciton that we see this break down. scientific discovery are descriptive, and we apply that back onto nature. it is only by happenstance that our applications have worked, we can see that the easy descriptive stuff has already been plucked, and now we enter a more uncertain world, where results are no longer as easy to get, see the failures of string theory
- the wilderness is constructed, and not only is it constructed, it is banal, and it is only exoitic as a orientalist fashion
- astromer by undergrad training, ai programmer by trade
